# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
#
# SPDX-License-Identifier: Apache-2.0
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
"""Op-level partial TTNN port for `ace_step_audio_tokenizer` of ACE-Step/acestep-v15-base.

AceStepAudioTokenizer == audio_acoustic_proj -> attention_pooler -> quantizer
(ResidualFSQ). Per the HF reference forward there is no other glue. This port
applies audio_acoustic_proj (64 -> 2048) itself, then delegates pooling to the
attention_pooler leaf stub and quantization to the residual_f_s_q leaf stub
(which in turn delegates the per-layer FSQ quantization to the f_s_q leaf stub).

HF reference: transformers/src/transformers/models/acestep/modeling_acestep.py"""

from __future__ import annotations

import transformers

import ttnn
from models.demos.hf_eager.acestep_v15_base._stubs.attention_pooler import build as _pooler_build
from models.demos.hf_eager.acestep_v15_base._stubs.residual_f_s_q import build as _rfsq_build

HF_MODEL_ID = "ACE-Step/acestep-v15-base"
_CANDIDATE_SUBMODULE_PATHS = ["tokenizer"]


def _log_runtime_fallback(helper, kind, reason):
    """Append a structured CPU-fallback event for the planner reporter.

    Best-effort; never raises and never blocks the test. Writes to
    `<demo_dir>/_runtime_fallbacks.jsonl` (or the path in env
    TT_HW_PLANNER_RUNTIME_FALLBACK_LOG). The planner truncates this file
    before each pytest invocation and consumes it afterwards.
    """
    try:
        import json as _json
        import os as _os
        import sys as _sys
        import time as _time
        from pathlib import Path as _Path

        _sys.stderr.write("[%s_CPU_FALLBACK] %s: %s\n" % (kind.upper(), helper, reason))
        log_env = _os.environ.get("TT_HW_PLANNER_RUNTIME_FALLBACK_LOG")
        if log_env:
            log_path = _Path(log_env)
        else:
            # _stubs/<safe>.py  ->  demo_dir = parents[1]
            log_path = _Path(__file__).resolve().parents[1] / "_runtime_fallbacks.jsonl"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        ev = {
            "component": _Path(__file__).stem,
            "helper": helper,
            "kind": kind,
            "reason": reason,
            "ts": _time.time(),
        }
        with log_path.open("a") as f:
            f.write(_json.dumps(ev) + "\n")
    except Exception:
        pass


def _resolve(obj, dotted):
    cur = obj
    for tok in dotted.replace("[", ".").replace("]", "").split("."):
        if tok == "":
            continue
        if tok.isdigit():
            cur = cur[int(tok)]
        else:
            cur = getattr(cur, tok)
    return cur


def _coerce_to_torch(x):
    try:
        import ttnn as _ttnn

        if isinstance(x, _ttnn.Tensor):
            import torch as _torch

            t = _ttnn.to_torch(x)
            # Bug Y fix (2026-05-23 live-run sam2-hiera-tiny)
            if t.is_floating_point():
                if t.dtype != _torch.float32:
                    t = t.to(_torch.float32)
            elif t.dtype != _torch.bool:
                t = t.to(_torch.long)
            return t
    except Exception:
        pass
    if isinstance(x, tuple):
        return tuple(_coerce_to_torch(e) for e in x)
    if isinstance(x, list):
        return [_coerce_to_torch(e) for e in x]
    if isinstance(x, dict):
        return {k: _coerce_to_torch(v) for k, v in x.items()}
    return x


class AceStepAudioTokenizer:
    def __init__(self, device, torch_module):
        self.device = device
        self._torch_module = torch_module
        sd = torch_module.state_dict()

        # op-REUSE: audio_acoustic_proj (Linear 64 -> 2048, bias=True). Applied by
        # the tokenizer itself before pooling, producing the [1, 10, 5, 2048] the
        # attention_pooler stub consumes.
        self.w_audio_acoustic_proj_weight = ttnn.from_torch(
            sd["audio_acoustic_proj.weight"].T.contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )
        self.w_audio_acoustic_proj_bias = ttnn.from_torch(
            sd["audio_acoustic_proj.bias"].reshape(1, -1), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # Delegate pooling and quantization to the leaf stubs so they are actually
        # invoked at runtime (attention_pooler; residual_f_s_q -> f_s_q).
        self._pooler_stub = _pooler_build(device, torch_module.attention_pooler)
        self._rfsq_stub = _rfsq_build(device, torch_module.quantizer)

    def _mm_cfg(self):
        return ttnn.WormholeComputeKernelConfig(
            math_fidelity=ttnn.MathFidelity.HiFi4,
            math_approx_mode=False,
            fp32_dest_acc_en=True,
            packer_l1_acc=True,
        )

    def _lin_f32(self, x, weight, bias, compute_kernel_config):
        return ttnn.linear(
            x,
            ttnn.typecast(weight, ttnn.float32),
            bias=ttnn.typecast(bias, ttnn.float32),
            compute_kernel_config=compute_kernel_config,
        )

    def __call__(self, hidden_states):
        # hidden_states: (B, T, P, D_in) with P = pool_window_size (5) and
        # D_in = audio_acoustic_hidden_dim (64).
        B, T, P, D_in = tuple(hidden_states.shape)
        hidden_size = 2048
        mm = self._mm_cfg()

        # audio_acoustic_proj: 64 -> 2048, elementwise over (B, T, P), in fp32/HiFi4.
        x = ttnn.typecast(hidden_states, ttnn.float32)
        x = ttnn.reshape(x, (B * T * P, D_in))
        x = self._lin_f32(x, self.w_audio_acoustic_proj_weight, self.w_audio_acoustic_proj_bias, mm)
        x = ttnn.reshape(x, (B, T, P, hidden_size))

        # attention_pooler stub concatenates a bf16 special token onto its input,
        # so feed it bf16 [B, T, P, 2048] exactly as it graduated.
        x = ttnn.typecast(x, ttnn.bfloat16)
        pooled = self._pooler_stub(x)

        # quantizer (ResidualFSQ): [B, T, 2048] -> (quantized[B,T,2048], indices[B,T,1]).
        quantized, indices = self._rfsq_stub(pooled)
        return quantized, indices


def build(device, torch_module):
    return AceStepAudioTokenizer(device, torch_module)


_instance = None


def ace_step_audio_tokenizer(*args, **kwargs):
    global _instance
    if _instance is None:
        model = transformers.AutoModel.from_pretrained(
            HF_MODEL_ID, trust_remote_code=True, torch_dtype="bfloat16", low_cpu_mem_usage=True
        )
        model.eval()
        torch_sub = None
        for path in _CANDIDATE_SUBMODULE_PATHS:
            try:
                torch_sub = _resolve(model, path)
                break
            except (AttributeError, IndexError, KeyError, TypeError):
                continue
        if torch_sub is None:
            raise RuntimeError("partial-stub: could not resolve `ace_step_audio_tokenizer`")
        _instance = build(ttnn.open_device(device_id=0), torch_sub)
    return _instance(*args, **kwargs)
