# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
#
# SPDX-License-Identifier: Apache-2.0
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
"""Op-level partial TTNN port for `ace_step_condition_encoder` of ACE-Step/acestep-v15-base.

Generated deterministically by `tt_hw_planner op-synth`.
Weight loading and op-REUSE/op-ADAPT helpers below are
machine-emitted from the HF reference and DO NOT need LLM
review. The `__call__` implementation falls back to HF
torch so the bring-up smoke test passes immediately;
the LLM's only remaining job is to rewrite `__call__`
to call the pre-bound `_apply_*` helpers in the right
order and fill any op-NEW gaps inline.

Pre-bound deterministic helpers (op palette):
#   self._apply_text_projector(x) -> ttnn.linear  (in=1024, out=2048, bias=False)
#   self._apply_lyric_encoder_embed_tokens(x) -> ttnn.linear  (in=1024, out=2048, bias=True)
#   self._apply_lyric_encoder_layers_0_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_0_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_0_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_0_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_0_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_0_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_0_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_0_mlp_act_fn(x) -> ttnn.silu
#   self._apply_lyric_encoder_layers_1_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_1_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_1_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_1_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_1_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_1_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_1_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_1_mlp_act_fn(x) -> ttnn.silu
#   self._apply_lyric_encoder_layers_2_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_2_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_2_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_2_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_2_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_2_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_2_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_2_mlp_act_fn(x) -> ttnn.silu
#   self._apply_lyric_encoder_layers_3_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_3_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_3_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_3_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_3_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_3_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_3_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_3_mlp_act_fn(x) -> ttnn.silu
#   self._apply_lyric_encoder_layers_4_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_4_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_4_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_4_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_4_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_4_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_4_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_4_mlp_act_fn(x) -> ttnn.silu
#   self._apply_lyric_encoder_layers_5_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_5_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_5_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_5_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_5_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_5_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_5_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_5_mlp_act_fn(x) -> ttnn.silu
#   self._apply_lyric_encoder_layers_6_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_6_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_6_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_6_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_6_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_6_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_6_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_6_mlp_act_fn(x) -> ttnn.silu
#   self._apply_lyric_encoder_layers_7_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_7_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_7_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_lyric_encoder_layers_7_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_7_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_7_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_lyric_encoder_layers_7_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_lyric_encoder_layers_7_mlp_act_fn(x) -> ttnn.silu
#   self._apply_timbre_encoder_embed_tokens(x) -> ttnn.linear  (in=64, out=2048, bias=True)
#   self._apply_timbre_encoder_layers_0_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_0_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_timbre_encoder_layers_0_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_timbre_encoder_layers_0_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_0_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_timbre_encoder_layers_0_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_timbre_encoder_layers_0_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_0_mlp_act_fn(x) -> ttnn.silu
#   self._apply_timbre_encoder_layers_1_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_1_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_timbre_encoder_layers_1_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_timbre_encoder_layers_1_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_1_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_timbre_encoder_layers_1_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_timbre_encoder_layers_1_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_1_mlp_act_fn(x) -> ttnn.silu
#   self._apply_timbre_encoder_layers_2_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_2_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_timbre_encoder_layers_2_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_timbre_encoder_layers_2_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_2_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_timbre_encoder_layers_2_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_timbre_encoder_layers_2_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_2_mlp_act_fn(x) -> ttnn.silu
#   self._apply_timbre_encoder_layers_3_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_3_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_timbre_encoder_layers_3_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_timbre_encoder_layers_3_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_3_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_timbre_encoder_layers_3_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_timbre_encoder_layers_3_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_timbre_encoder_layers_3_mlp_act_fn(x) -> ttnn.silu

LLM_GAPs (op-NEW — still need synthesis):
#   - lyric_encoder.norm  (Qwen3RMSNorm)
#   - lyric_encoder.rotary_emb  (Qwen3RotaryEmbedding)
#   - lyric_encoder.layers.0.self_attn.q_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.0.self_attn.k_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.0.input_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.0.post_attention_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.1.self_attn.q_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.1.self_attn.k_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.1.input_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.1.post_attention_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.2.self_attn.q_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.2.self_attn.k_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.2.input_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.2.post_attention_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.3.self_attn.q_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.3.self_attn.k_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.3.input_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.3.post_attention_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.4.self_attn.q_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.4.self_attn.k_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.4.input_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.4.post_attention_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.5.self_attn.q_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.5.self_attn.k_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.5.input_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.5.post_attention_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.6.self_attn.q_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.6.self_attn.k_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.6.input_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.6.post_attention_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.7.self_attn.q_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.7.self_attn.k_norm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.7.input_layernorm  (Qwen3RMSNorm)
#   - lyric_encoder.layers.7.post_attention_layernorm  (Qwen3RMSNorm)
#   - timbre_encoder.norm  (Qwen3RMSNorm)
#   - timbre_encoder.rotary_emb  (Qwen3RotaryEmbedding)
#   - timbre_encoder.layers.0.self_attn.q_norm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.0.self_attn.k_norm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.0.input_layernorm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.0.post_attention_layernorm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.1.self_attn.q_norm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.1.self_attn.k_norm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.1.input_layernorm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.1.post_attention_layernorm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.2.self_attn.q_norm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.2.self_attn.k_norm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.2.input_layernorm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.2.post_attention_layernorm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.3.self_attn.q_norm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.3.self_attn.k_norm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.3.input_layernorm  (Qwen3RMSNorm)
#   - timbre_encoder.layers.3.post_attention_layernorm  (Qwen3RMSNorm)

HF reference: transformers/src/transformers/models/acestep/modeling_acestep.py
Op counts: total=151  op-REUSE=99  op-ADAPT=0  op-NEW=52"""

from __future__ import annotations

import torch
import transformers

import ttnn

HF_MODEL_ID = "ACE-Step/acestep-v15-base"
_CANDIDATE_SUBMODULE_PATHS = ["encoder"]


def _log_runtime_fallback(helper, kind, reason):
    """Append a structured CPU-fallback event for the planner reporter.

    Best-effort; never raises and never blocks the test. Writes to
    `<demo_dir>/_runtime_fallbacks.jsonl` (or the path in env
    TT_HW_PLANNER_RUNTIME_FALLBACK_LOG). The planner truncates this file
    before each pytest invocation and consumes it afterwards.
    """
    try:
        import json as _json
        import os as _os
        import sys as _sys
        import time as _time
        from pathlib import Path as _Path

        _sys.stderr.write("[%s_CPU_FALLBACK] %s: %s\n" % (kind.upper(), helper, reason))
        log_env = _os.environ.get("TT_HW_PLANNER_RUNTIME_FALLBACK_LOG")
        if log_env:
            log_path = _Path(log_env)
        else:
            # _stubs/<safe>.py  ->  demo_dir = parents[1]
            log_path = _Path(__file__).resolve().parents[1] / "_runtime_fallbacks.jsonl"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        ev = {
            "component": _Path(__file__).stem,
            "helper": helper,
            "kind": kind,
            "reason": reason,
            "ts": _time.time(),
        }
        with log_path.open("a") as f:
            f.write(_json.dumps(ev) + "\n")
    except Exception:
        pass


_LLM_GAPS = [
    {"name": "lyric_encoder.norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.rotary_emb", "class": "Qwen3RotaryEmbedding", "notes": ""},
    {"name": "lyric_encoder.layers.0.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.0.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.0.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.0.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.1.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.1.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.1.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.1.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.2.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.2.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.2.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.2.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.3.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.3.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.3.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.3.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.4.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.4.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.4.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.4.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.5.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.5.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.5.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.5.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.6.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.6.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.6.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.6.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.7.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.7.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.7.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "lyric_encoder.layers.7.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.rotary_emb", "class": "Qwen3RotaryEmbedding", "notes": ""},
    {"name": "timbre_encoder.layers.0.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.0.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.0.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.0.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.1.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.1.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.1.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.1.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.2.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.2.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.2.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.2.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.3.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.3.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.3.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "timbre_encoder.layers.3.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
]


def _resolve(obj, dotted):
    cur = obj
    for tok in dotted.replace("[", ".").replace("]", "").split("."):
        if tok == "":
            continue
        if tok.isdigit():
            cur = cur[int(tok)]
        else:
            cur = getattr(cur, tok)
    return cur


def _coerce_to_torch(x):
    try:
        import ttnn as _ttnn

        if isinstance(x, _ttnn.Tensor):
            import torch as _torch

            t = _ttnn.to_torch(x)
            if t.is_floating_point():
                if t.dtype != _torch.float32:
                    t = t.to(_torch.float32)
            elif t.dtype != _torch.bool:
                t = t.to(_torch.long)
            return t
    except Exception:
        pass
    if isinstance(x, tuple):
        return tuple(_coerce_to_torch(e) for e in x)
    if isinstance(x, list):
        return [_coerce_to_torch(e) for e in x]
    if isinstance(x, dict):
        return {k: _coerce_to_torch(v) for k, v in x.items()}
    return x


class AceStepConditionEncoder:
    def __init__(self, device, torch_module):
        self.device = device
        self._torch_module = torch_module
        sd = torch_module.state_dict()
        # op-REUSE: text_projector  (Linear 1024 -> 2048, bias=False)
        self.w_text_projector_weight = ttnn.from_torch(
            sd["text_projector.weight"].T.contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # op-REUSE: lyric_encoder.embed_tokens  (Linear 1024 -> 2048, bias=True)
        self.w_lyric_encoder_embed_tokens_weight = ttnn.from_torch(
            sd["lyric_encoder.embed_tokens.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_lyric_encoder_embed_tokens_bias = ttnn.from_torch(
            sd["lyric_encoder.embed_tokens.bias"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.0.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_0_self_attn_q_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.0.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.0.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_0_self_attn_k_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.0.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.0.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_0_self_attn_v_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.0.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.0.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_0_self_attn_o_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.0.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.0.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_0_mlp_gate_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.0.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.0.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_0_mlp_up_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.0.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.0.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_lyric_encoder_layers_0_mlp_down_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.0.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.0.mlp.act_fn  (SILU)

        # op-REUSE: lyric_encoder.layers.1.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_1_self_attn_q_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.1.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.1.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_1_self_attn_k_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.1.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.1.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_1_self_attn_v_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.1.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.1.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_1_self_attn_o_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.1.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.1.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_1_mlp_gate_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.1.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.1.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_1_mlp_up_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.1.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.1.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_lyric_encoder_layers_1_mlp_down_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.1.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.1.mlp.act_fn  (SILU)

        # op-REUSE: lyric_encoder.layers.2.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_2_self_attn_q_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.2.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.2.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_2_self_attn_k_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.2.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.2.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_2_self_attn_v_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.2.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.2.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_2_self_attn_o_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.2.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.2.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_2_mlp_gate_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.2.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.2.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_2_mlp_up_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.2.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.2.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_lyric_encoder_layers_2_mlp_down_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.2.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.2.mlp.act_fn  (SILU)

        # op-REUSE: lyric_encoder.layers.3.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_3_self_attn_q_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.3.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.3.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_3_self_attn_k_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.3.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.3.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_3_self_attn_v_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.3.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.3.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_3_self_attn_o_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.3.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.3.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_3_mlp_gate_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.3.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.3.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_3_mlp_up_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.3.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.3.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_lyric_encoder_layers_3_mlp_down_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.3.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.3.mlp.act_fn  (SILU)

        # op-REUSE: lyric_encoder.layers.4.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_4_self_attn_q_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.4.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.4.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_4_self_attn_k_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.4.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.4.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_4_self_attn_v_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.4.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.4.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_4_self_attn_o_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.4.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.4.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_4_mlp_gate_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.4.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.4.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_4_mlp_up_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.4.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.4.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_lyric_encoder_layers_4_mlp_down_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.4.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.4.mlp.act_fn  (SILU)

        # op-REUSE: lyric_encoder.layers.5.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_5_self_attn_q_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.5.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.5.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_5_self_attn_k_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.5.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.5.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_5_self_attn_v_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.5.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.5.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_5_self_attn_o_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.5.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.5.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_5_mlp_gate_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.5.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.5.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_5_mlp_up_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.5.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.5.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_lyric_encoder_layers_5_mlp_down_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.5.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.5.mlp.act_fn  (SILU)

        # op-REUSE: lyric_encoder.layers.6.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_6_self_attn_q_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.6.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.6.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_6_self_attn_k_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.6.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.6.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_6_self_attn_v_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.6.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.6.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_6_self_attn_o_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.6.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.6.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_6_mlp_gate_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.6.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.6.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_6_mlp_up_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.6.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.6.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_lyric_encoder_layers_6_mlp_down_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.6.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.6.mlp.act_fn  (SILU)

        # op-REUSE: lyric_encoder.layers.7.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_7_self_attn_q_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.7.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.7.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_7_self_attn_k_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.7.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.7.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_lyric_encoder_layers_7_self_attn_v_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.7.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.7.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_lyric_encoder_layers_7_self_attn_o_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.7.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.7.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_7_mlp_gate_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.7.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.7.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_lyric_encoder_layers_7_mlp_up_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.7.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.7.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_lyric_encoder_layers_7_mlp_down_proj_weight = ttnn.from_torch(
            sd["lyric_encoder.layers.7.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: lyric_encoder.layers.7.mlp.act_fn  (SILU)

        # op-REUSE: timbre_encoder.embed_tokens  (Linear 64 -> 2048, bias=True)
        self.w_timbre_encoder_embed_tokens_weight = ttnn.from_torch(
            sd["timbre_encoder.embed_tokens.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_timbre_encoder_embed_tokens_bias = ttnn.from_torch(
            sd["timbre_encoder.embed_tokens.bias"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.0.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_timbre_encoder_layers_0_self_attn_q_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.0.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.0.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_timbre_encoder_layers_0_self_attn_k_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.0.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.0.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_timbre_encoder_layers_0_self_attn_v_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.0.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.0.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_timbre_encoder_layers_0_self_attn_o_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.0.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.0.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_timbre_encoder_layers_0_mlp_gate_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.0.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.0.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_timbre_encoder_layers_0_mlp_up_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.0.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.0.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_timbre_encoder_layers_0_mlp_down_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.0.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.0.mlp.act_fn  (SILU)

        # op-REUSE: timbre_encoder.layers.1.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_timbre_encoder_layers_1_self_attn_q_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.1.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.1.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_timbre_encoder_layers_1_self_attn_k_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.1.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.1.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_timbre_encoder_layers_1_self_attn_v_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.1.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.1.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_timbre_encoder_layers_1_self_attn_o_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.1.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.1.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_timbre_encoder_layers_1_mlp_gate_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.1.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.1.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_timbre_encoder_layers_1_mlp_up_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.1.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.1.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_timbre_encoder_layers_1_mlp_down_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.1.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.1.mlp.act_fn  (SILU)

        # op-REUSE: timbre_encoder.layers.2.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_timbre_encoder_layers_2_self_attn_q_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.2.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.2.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_timbre_encoder_layers_2_self_attn_k_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.2.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.2.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_timbre_encoder_layers_2_self_attn_v_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.2.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.2.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_timbre_encoder_layers_2_self_attn_o_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.2.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.2.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_timbre_encoder_layers_2_mlp_gate_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.2.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.2.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_timbre_encoder_layers_2_mlp_up_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.2.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.2.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_timbre_encoder_layers_2_mlp_down_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.2.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.2.mlp.act_fn  (SILU)

        # op-REUSE: timbre_encoder.layers.3.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_timbre_encoder_layers_3_self_attn_q_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.3.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.3.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_timbre_encoder_layers_3_self_attn_k_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.3.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.3.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_timbre_encoder_layers_3_self_attn_v_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.3.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.3.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_timbre_encoder_layers_3_self_attn_o_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.3.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.3.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_timbre_encoder_layers_3_mlp_gate_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.3.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.3.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_timbre_encoder_layers_3_mlp_up_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.3.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.3.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_timbre_encoder_layers_3_mlp_down_proj_weight = ttnn.from_torch(
            sd["timbre_encoder.layers.3.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: timbre_encoder.layers.3.mlp.act_fn  (SILU)

    # ---- op-NEW gap helpers (RMSNorm / RoPE / GQA attention / sequence packing) ----
    _RMS_EPS = 1e-6
    _ROPE_THETA = 1000000.0
    _HEAD_DIM = 128
    _NUM_HEADS = 16
    _NUM_KV_HEADS = 8
    _HIDDEN_SIZE = 2048

    def _get_weight(self, dotted_path, dim):
        cache_attr = "_w_cache_" + dotted_path.replace(".", "_")
        cached = getattr(self, cache_attr, None)
        if cached is None:
            w = self._torch_module.state_dict()[dotted_path].reshape(1, dim)
            cached = ttnn.from_torch(w, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device)
            setattr(self, cache_attr, cached)
        return cached

    def _rms_norm(self, x, weight):
        return ttnn.rms_norm(x, epsilon=self._RMS_EPS, weight=weight)

    def _rope_tables(self, seq_len):
        cache_attr = f"_rope_cache_{seq_len}"
        cached = getattr(self, cache_attr, None)
        if cached is None:
            head_dim = self._HEAD_DIM
            inv_freq = 1.0 / (self._ROPE_THETA ** (torch.arange(0, head_dim, 2, dtype=torch.float32) / head_dim))
            positions = torch.arange(seq_len, dtype=torch.float32)
            freqs = torch.outer(positions, inv_freq)
            emb = torch.cat([freqs, freqs], dim=-1)
            cos = emb.cos().to(torch.bfloat16).reshape(1, 1, seq_len, head_dim)
            sin = emb.sin().to(torch.bfloat16).reshape(1, 1, seq_len, head_dim)
            cos_tt = ttnn.from_torch(cos, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device)
            sin_tt = ttnn.from_torch(sin, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device)
            cached = (cos_tt, sin_tt)
            setattr(self, cache_attr, cached)
        return cached

    def _apply_rope(self, x, cos, sin):
        b, h, t, d = x.shape[0], x.shape[1], x.shape[2], x.shape[3]
        half = d // 2
        x1 = ttnn.slice(x, [0, 0, 0, 0], [b, h, t, half])
        x2 = ttnn.slice(x, [0, 0, 0, half], [b, h, t, d])
        rotated = ttnn.concat([ttnn.neg(x2), x1], dim=-1)
        return ttnn.add(ttnn.multiply(x, cos), ttnn.multiply(rotated, sin))

    def _split_heads(self, x, num_heads, head_dim):
        b, t = x.shape[0], x.shape[1]
        x = ttnn.reshape(x, (b, t, num_heads, head_dim))
        return ttnn.permute(x, (0, 2, 1, 3))

    def _merge_heads(self, x, num_heads, head_dim):
        b, t = x.shape[0], x.shape[2]
        x = ttnn.permute(x, (0, 2, 1, 3))
        return ttnn.reshape(x, (b, t, num_heads * head_dim))

    def _self_attention(self, x, q_fn, k_fn, v_fn, o_fn, q_norm_w, k_norm_w, cos, sin):
        head_dim = self._HEAD_DIM
        q = self._split_heads(q_fn(x), self._NUM_HEADS, head_dim)
        k = self._split_heads(k_fn(x), self._NUM_KV_HEADS, head_dim)
        v = self._split_heads(v_fn(x), self._NUM_KV_HEADS, head_dim)
        q = self._rms_norm(q, q_norm_w)
        k = self._rms_norm(k, k_norm_w)
        q = self._apply_rope(q, cos, sin)
        k = self._apply_rope(k, cos, sin)
        attn = ttnn.transformer.scaled_dot_product_attention(q, k, v, is_causal=False)
        attn = self._merge_heads(attn, self._NUM_HEADS, head_dim)
        return o_fn(attn)

    def _encoder_layer(self, x, prefix, layer_idx, q_fn, k_fn, v_fn, o_fn, gate_fn, up_fn, down_fn, act_fn, cos, sin):
        q_norm_w = self._get_weight(f"{prefix}.layers.{layer_idx}.self_attn.q_norm.weight", self._HEAD_DIM)
        k_norm_w = self._get_weight(f"{prefix}.layers.{layer_idx}.self_attn.k_norm.weight", self._HEAD_DIM)
        in_ln_w = self._get_weight(f"{prefix}.layers.{layer_idx}.input_layernorm.weight", self._HIDDEN_SIZE)
        post_ln_w = self._get_weight(f"{prefix}.layers.{layer_idx}.post_attention_layernorm.weight", self._HIDDEN_SIZE)

        residual = x
        h = self._rms_norm(x, in_ln_w)
        attn_out = self._self_attention(h, q_fn, k_fn, v_fn, o_fn, q_norm_w, k_norm_w, cos, sin)
        x = ttnn.add(residual, attn_out)

        residual = x
        h = self._rms_norm(x, post_ln_w)
        gate = act_fn(gate_fn(h))
        up = up_fn(h)
        mlp_out = down_fn(ttnn.multiply(gate, up))
        x = ttnn.add(residual, mlp_out)
        return x

    def _pack_sequences(self, hidden1, hidden2, mask1_torch, mask2_torch):
        hidden_cat = ttnn.concat([hidden1, hidden2], dim=1)
        mask_cat_torch = torch.cat([mask1_torch, mask2_torch], dim=1).to(torch.float32)
        b, l = mask_cat_torch.shape
        sort_idx = mask_cat_torch.argsort(dim=1, descending=True, stable=True)
        perm = torch.eye(l, dtype=torch.float32)[sort_idx].to(torch.bfloat16)
        lengths = (mask_cat_torch > 0).sum(dim=1)
        new_mask_torch = torch.arange(l, dtype=torch.long).unsqueeze(0) < lengths.unsqueeze(1)
        perm_tt = ttnn.from_torch(perm, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device)
        hidden_packed = ttnn.matmul(perm_tt, hidden_cat)
        return hidden_packed, new_mask_torch

    def _apply_text_projector(self, x):
        return ttnn.linear(x, self.w_text_projector_weight)

    def _apply_lyric_encoder_embed_tokens(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_embed_tokens_weight, bias=self.w_lyric_encoder_embed_tokens_bias)

    def _apply_lyric_encoder_layers_0_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_0_self_attn_q_proj_weight)

    def _apply_lyric_encoder_layers_0_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_0_self_attn_k_proj_weight)

    def _apply_lyric_encoder_layers_0_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_0_self_attn_v_proj_weight)

    def _apply_lyric_encoder_layers_0_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_0_self_attn_o_proj_weight)

    def _apply_lyric_encoder_layers_0_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_0_mlp_gate_proj_weight)

    def _apply_lyric_encoder_layers_0_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_0_mlp_up_proj_weight)

    def _apply_lyric_encoder_layers_0_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_0_mlp_down_proj_weight)

    def _apply_lyric_encoder_layers_0_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_lyric_encoder_layers_1_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_1_self_attn_q_proj_weight)

    def _apply_lyric_encoder_layers_1_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_1_self_attn_k_proj_weight)

    def _apply_lyric_encoder_layers_1_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_1_self_attn_v_proj_weight)

    def _apply_lyric_encoder_layers_1_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_1_self_attn_o_proj_weight)

    def _apply_lyric_encoder_layers_1_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_1_mlp_gate_proj_weight)

    def _apply_lyric_encoder_layers_1_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_1_mlp_up_proj_weight)

    def _apply_lyric_encoder_layers_1_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_1_mlp_down_proj_weight)

    def _apply_lyric_encoder_layers_1_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_lyric_encoder_layers_2_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_2_self_attn_q_proj_weight)

    def _apply_lyric_encoder_layers_2_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_2_self_attn_k_proj_weight)

    def _apply_lyric_encoder_layers_2_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_2_self_attn_v_proj_weight)

    def _apply_lyric_encoder_layers_2_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_2_self_attn_o_proj_weight)

    def _apply_lyric_encoder_layers_2_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_2_mlp_gate_proj_weight)

    def _apply_lyric_encoder_layers_2_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_2_mlp_up_proj_weight)

    def _apply_lyric_encoder_layers_2_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_2_mlp_down_proj_weight)

    def _apply_lyric_encoder_layers_2_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_lyric_encoder_layers_3_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_3_self_attn_q_proj_weight)

    def _apply_lyric_encoder_layers_3_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_3_self_attn_k_proj_weight)

    def _apply_lyric_encoder_layers_3_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_3_self_attn_v_proj_weight)

    def _apply_lyric_encoder_layers_3_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_3_self_attn_o_proj_weight)

    def _apply_lyric_encoder_layers_3_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_3_mlp_gate_proj_weight)

    def _apply_lyric_encoder_layers_3_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_3_mlp_up_proj_weight)

    def _apply_lyric_encoder_layers_3_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_3_mlp_down_proj_weight)

    def _apply_lyric_encoder_layers_3_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_lyric_encoder_layers_4_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_4_self_attn_q_proj_weight)

    def _apply_lyric_encoder_layers_4_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_4_self_attn_k_proj_weight)

    def _apply_lyric_encoder_layers_4_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_4_self_attn_v_proj_weight)

    def _apply_lyric_encoder_layers_4_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_4_self_attn_o_proj_weight)

    def _apply_lyric_encoder_layers_4_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_4_mlp_gate_proj_weight)

    def _apply_lyric_encoder_layers_4_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_4_mlp_up_proj_weight)

    def _apply_lyric_encoder_layers_4_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_4_mlp_down_proj_weight)

    def _apply_lyric_encoder_layers_4_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_lyric_encoder_layers_5_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_5_self_attn_q_proj_weight)

    def _apply_lyric_encoder_layers_5_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_5_self_attn_k_proj_weight)

    def _apply_lyric_encoder_layers_5_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_5_self_attn_v_proj_weight)

    def _apply_lyric_encoder_layers_5_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_5_self_attn_o_proj_weight)

    def _apply_lyric_encoder_layers_5_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_5_mlp_gate_proj_weight)

    def _apply_lyric_encoder_layers_5_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_5_mlp_up_proj_weight)

    def _apply_lyric_encoder_layers_5_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_5_mlp_down_proj_weight)

    def _apply_lyric_encoder_layers_5_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_lyric_encoder_layers_6_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_6_self_attn_q_proj_weight)

    def _apply_lyric_encoder_layers_6_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_6_self_attn_k_proj_weight)

    def _apply_lyric_encoder_layers_6_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_6_self_attn_v_proj_weight)

    def _apply_lyric_encoder_layers_6_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_6_self_attn_o_proj_weight)

    def _apply_lyric_encoder_layers_6_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_6_mlp_gate_proj_weight)

    def _apply_lyric_encoder_layers_6_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_6_mlp_up_proj_weight)

    def _apply_lyric_encoder_layers_6_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_6_mlp_down_proj_weight)

    def _apply_lyric_encoder_layers_6_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_lyric_encoder_layers_7_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_7_self_attn_q_proj_weight)

    def _apply_lyric_encoder_layers_7_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_7_self_attn_k_proj_weight)

    def _apply_lyric_encoder_layers_7_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_7_self_attn_v_proj_weight)

    def _apply_lyric_encoder_layers_7_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_7_self_attn_o_proj_weight)

    def _apply_lyric_encoder_layers_7_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_7_mlp_gate_proj_weight)

    def _apply_lyric_encoder_layers_7_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_7_mlp_up_proj_weight)

    def _apply_lyric_encoder_layers_7_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_lyric_encoder_layers_7_mlp_down_proj_weight)

    def _apply_lyric_encoder_layers_7_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_timbre_encoder_embed_tokens(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_embed_tokens_weight, bias=self.w_timbre_encoder_embed_tokens_bias)

    def _apply_timbre_encoder_layers_0_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_0_self_attn_q_proj_weight)

    def _apply_timbre_encoder_layers_0_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_0_self_attn_k_proj_weight)

    def _apply_timbre_encoder_layers_0_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_0_self_attn_v_proj_weight)

    def _apply_timbre_encoder_layers_0_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_0_self_attn_o_proj_weight)

    def _apply_timbre_encoder_layers_0_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_0_mlp_gate_proj_weight)

    def _apply_timbre_encoder_layers_0_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_0_mlp_up_proj_weight)

    def _apply_timbre_encoder_layers_0_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_0_mlp_down_proj_weight)

    def _apply_timbre_encoder_layers_0_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_timbre_encoder_layers_1_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_1_self_attn_q_proj_weight)

    def _apply_timbre_encoder_layers_1_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_1_self_attn_k_proj_weight)

    def _apply_timbre_encoder_layers_1_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_1_self_attn_v_proj_weight)

    def _apply_timbre_encoder_layers_1_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_1_self_attn_o_proj_weight)

    def _apply_timbre_encoder_layers_1_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_1_mlp_gate_proj_weight)

    def _apply_timbre_encoder_layers_1_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_1_mlp_up_proj_weight)

    def _apply_timbre_encoder_layers_1_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_1_mlp_down_proj_weight)

    def _apply_timbre_encoder_layers_1_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_timbre_encoder_layers_2_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_2_self_attn_q_proj_weight)

    def _apply_timbre_encoder_layers_2_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_2_self_attn_k_proj_weight)

    def _apply_timbre_encoder_layers_2_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_2_self_attn_v_proj_weight)

    def _apply_timbre_encoder_layers_2_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_2_self_attn_o_proj_weight)

    def _apply_timbre_encoder_layers_2_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_2_mlp_gate_proj_weight)

    def _apply_timbre_encoder_layers_2_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_2_mlp_up_proj_weight)

    def _apply_timbre_encoder_layers_2_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_2_mlp_down_proj_weight)

    def _apply_timbre_encoder_layers_2_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_timbre_encoder_layers_3_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_3_self_attn_q_proj_weight)

    def _apply_timbre_encoder_layers_3_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_3_self_attn_k_proj_weight)

    def _apply_timbre_encoder_layers_3_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_3_self_attn_v_proj_weight)

    def _apply_timbre_encoder_layers_3_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_3_self_attn_o_proj_weight)

    def _apply_timbre_encoder_layers_3_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_3_mlp_gate_proj_weight)

    def _apply_timbre_encoder_layers_3_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_3_mlp_up_proj_weight)

    def _apply_timbre_encoder_layers_3_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_timbre_encoder_layers_3_mlp_down_proj_weight)

    def _apply_timbre_encoder_layers_3_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def __call__(
        self,
        text_hidden_states=None,
        text_attention_mask=None,
        lyric_hidden_states=None,
        lyric_attention_mask=None,
        refer_audio_acoustic_hidden_states_packed=None,
        refer_audio_order_mask=None,
    ):
        text_mask_torch = text_attention_mask
        lyric_mask_torch = lyric_attention_mask

        text_tt = (
            text_hidden_states
            if isinstance(text_hidden_states, ttnn.Tensor)
            else ttnn.from_torch(text_hidden_states, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device)
        )
        lyric_tt = (
            lyric_hidden_states
            if isinstance(lyric_hidden_states, ttnn.Tensor)
            else ttnn.from_torch(lyric_hidden_states, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device)
        )
        refer_audio_tt = (
            refer_audio_acoustic_hidden_states_packed
            if isinstance(refer_audio_acoustic_hidden_states_packed, ttnn.Tensor)
            else ttnn.from_torch(
                refer_audio_acoustic_hidden_states_packed,
                dtype=ttnn.bfloat16,
                layout=ttnn.TILE_LAYOUT,
                device=self.device,
            )
        )

        text_proj = self._apply_text_projector(text_tt)

        lyric_seq_len = (
            lyric_hidden_states.shape[1]
            if isinstance(lyric_hidden_states, ttnn.Tensor)
            else lyric_hidden_states.shape[1]
        )
        lyric_embed = self._apply_lyric_encoder_embed_tokens(lyric_tt)
        lyric_cos, lyric_sin = self._rope_tables(lyric_seq_len)
        lyric_embed = self._process_lyric_encoder_layer_0(lyric_embed, lyric_cos, lyric_sin)
        lyric_embed = self._process_lyric_encoder_layer_1(lyric_embed, lyric_cos, lyric_sin)
        lyric_embed = self._process_lyric_encoder_layer_2(lyric_embed, lyric_cos, lyric_sin)
        lyric_embed = self._process_lyric_encoder_layer_3(lyric_embed, lyric_cos, lyric_sin)
        lyric_embed = self._process_lyric_encoder_layer_4(lyric_embed, lyric_cos, lyric_sin)
        lyric_embed = self._process_lyric_encoder_layer_5(lyric_embed, lyric_cos, lyric_sin)
        lyric_embed = self._process_lyric_encoder_layer_6(lyric_embed, lyric_cos, lyric_sin)
        lyric_embed = self._process_lyric_encoder_layer_7(lyric_embed, lyric_cos, lyric_sin)
        lyric_embed = self._rms_norm(lyric_embed, self._get_weight("lyric_encoder.norm.weight", self._HIDDEN_SIZE))

        timbre_seq_len = (
            refer_audio_acoustic_hidden_states_packed.shape[1]
            if isinstance(refer_audio_acoustic_hidden_states_packed, ttnn.Tensor)
            else refer_audio_acoustic_hidden_states_packed.shape[1]
        )
        timbre_embed = self._apply_timbre_encoder_embed_tokens(refer_audio_tt)
        timbre_cos, timbre_sin = self._rope_tables(timbre_seq_len)
        timbre_embed = self._process_timbre_encoder_layer_0(timbre_embed, timbre_cos, timbre_sin)
        timbre_embed = self._process_timbre_encoder_layer_1(timbre_embed, timbre_cos, timbre_sin)
        timbre_embed = self._process_timbre_encoder_layer_2(timbre_embed, timbre_cos, timbre_sin)
        timbre_embed = self._process_timbre_encoder_layer_3(timbre_embed, timbre_cos, timbre_sin)
        timbre_embed = self._rms_norm(timbre_embed, self._get_weight("timbre_encoder.norm.weight", self._HIDDEN_SIZE))

        b = timbre_embed.shape[0]
        timbre_pooled = ttnn.slice(timbre_embed, [0, 0, 0], [b, 1, self._HIDDEN_SIZE])

        out_batch = int(refer_audio_order_mask.max().item()) + 1
        timbre_mask_torch = torch.ones((out_batch, 1), dtype=torch.float32)

        packed1, mask1_torch = self._pack_sequences(lyric_embed, timbre_pooled, lyric_mask_torch, timbre_mask_torch)
        packed2, mask2_torch = self._pack_sequences(packed1, text_proj, mask1_torch, text_mask_torch)

        attention_mask = ttnn.from_torch(
            mask2_torch.to(torch.int32), dtype=ttnn.uint32, layout=ttnn.ROW_MAJOR_LAYOUT, device=self.device
        )

        return (packed2, attention_mask)

    def _process_lyric_encoder_layer_0(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "lyric_encoder",
            0,
            self._apply_lyric_encoder_layers_0_self_attn_q_proj,
            self._apply_lyric_encoder_layers_0_self_attn_k_proj,
            self._apply_lyric_encoder_layers_0_self_attn_v_proj,
            self._apply_lyric_encoder_layers_0_self_attn_o_proj,
            self._apply_lyric_encoder_layers_0_mlp_gate_proj,
            self._apply_lyric_encoder_layers_0_mlp_up_proj,
            self._apply_lyric_encoder_layers_0_mlp_down_proj,
            self._apply_lyric_encoder_layers_0_mlp_act_fn,
            cos,
            sin,
        )

    def _process_lyric_encoder_layer_1(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "lyric_encoder",
            1,
            self._apply_lyric_encoder_layers_1_self_attn_q_proj,
            self._apply_lyric_encoder_layers_1_self_attn_k_proj,
            self._apply_lyric_encoder_layers_1_self_attn_v_proj,
            self._apply_lyric_encoder_layers_1_self_attn_o_proj,
            self._apply_lyric_encoder_layers_1_mlp_gate_proj,
            self._apply_lyric_encoder_layers_1_mlp_up_proj,
            self._apply_lyric_encoder_layers_1_mlp_down_proj,
            self._apply_lyric_encoder_layers_1_mlp_act_fn,
            cos,
            sin,
        )

    def _process_lyric_encoder_layer_2(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "lyric_encoder",
            2,
            self._apply_lyric_encoder_layers_2_self_attn_q_proj,
            self._apply_lyric_encoder_layers_2_self_attn_k_proj,
            self._apply_lyric_encoder_layers_2_self_attn_v_proj,
            self._apply_lyric_encoder_layers_2_self_attn_o_proj,
            self._apply_lyric_encoder_layers_2_mlp_gate_proj,
            self._apply_lyric_encoder_layers_2_mlp_up_proj,
            self._apply_lyric_encoder_layers_2_mlp_down_proj,
            self._apply_lyric_encoder_layers_2_mlp_act_fn,
            cos,
            sin,
        )

    def _process_lyric_encoder_layer_3(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "lyric_encoder",
            3,
            self._apply_lyric_encoder_layers_3_self_attn_q_proj,
            self._apply_lyric_encoder_layers_3_self_attn_k_proj,
            self._apply_lyric_encoder_layers_3_self_attn_v_proj,
            self._apply_lyric_encoder_layers_3_self_attn_o_proj,
            self._apply_lyric_encoder_layers_3_mlp_gate_proj,
            self._apply_lyric_encoder_layers_3_mlp_up_proj,
            self._apply_lyric_encoder_layers_3_mlp_down_proj,
            self._apply_lyric_encoder_layers_3_mlp_act_fn,
            cos,
            sin,
        )

    def _process_lyric_encoder_layer_4(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "lyric_encoder",
            4,
            self._apply_lyric_encoder_layers_4_self_attn_q_proj,
            self._apply_lyric_encoder_layers_4_self_attn_k_proj,
            self._apply_lyric_encoder_layers_4_self_attn_v_proj,
            self._apply_lyric_encoder_layers_4_self_attn_o_proj,
            self._apply_lyric_encoder_layers_4_mlp_gate_proj,
            self._apply_lyric_encoder_layers_4_mlp_up_proj,
            self._apply_lyric_encoder_layers_4_mlp_down_proj,
            self._apply_lyric_encoder_layers_4_mlp_act_fn,
            cos,
            sin,
        )

    def _process_lyric_encoder_layer_5(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "lyric_encoder",
            5,
            self._apply_lyric_encoder_layers_5_self_attn_q_proj,
            self._apply_lyric_encoder_layers_5_self_attn_k_proj,
            self._apply_lyric_encoder_layers_5_self_attn_v_proj,
            self._apply_lyric_encoder_layers_5_self_attn_o_proj,
            self._apply_lyric_encoder_layers_5_mlp_gate_proj,
            self._apply_lyric_encoder_layers_5_mlp_up_proj,
            self._apply_lyric_encoder_layers_5_mlp_down_proj,
            self._apply_lyric_encoder_layers_5_mlp_act_fn,
            cos,
            sin,
        )

    def _process_lyric_encoder_layer_6(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "lyric_encoder",
            6,
            self._apply_lyric_encoder_layers_6_self_attn_q_proj,
            self._apply_lyric_encoder_layers_6_self_attn_k_proj,
            self._apply_lyric_encoder_layers_6_self_attn_v_proj,
            self._apply_lyric_encoder_layers_6_self_attn_o_proj,
            self._apply_lyric_encoder_layers_6_mlp_gate_proj,
            self._apply_lyric_encoder_layers_6_mlp_up_proj,
            self._apply_lyric_encoder_layers_6_mlp_down_proj,
            self._apply_lyric_encoder_layers_6_mlp_act_fn,
            cos,
            sin,
        )

    def _process_lyric_encoder_layer_7(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "lyric_encoder",
            7,
            self._apply_lyric_encoder_layers_7_self_attn_q_proj,
            self._apply_lyric_encoder_layers_7_self_attn_k_proj,
            self._apply_lyric_encoder_layers_7_self_attn_v_proj,
            self._apply_lyric_encoder_layers_7_self_attn_o_proj,
            self._apply_lyric_encoder_layers_7_mlp_gate_proj,
            self._apply_lyric_encoder_layers_7_mlp_up_proj,
            self._apply_lyric_encoder_layers_7_mlp_down_proj,
            self._apply_lyric_encoder_layers_7_mlp_act_fn,
            cos,
            sin,
        )

    def _process_timbre_encoder_layer_0(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "timbre_encoder",
            0,
            self._apply_timbre_encoder_layers_0_self_attn_q_proj,
            self._apply_timbre_encoder_layers_0_self_attn_k_proj,
            self._apply_timbre_encoder_layers_0_self_attn_v_proj,
            self._apply_timbre_encoder_layers_0_self_attn_o_proj,
            self._apply_timbre_encoder_layers_0_mlp_gate_proj,
            self._apply_timbre_encoder_layers_0_mlp_up_proj,
            self._apply_timbre_encoder_layers_0_mlp_down_proj,
            self._apply_timbre_encoder_layers_0_mlp_act_fn,
            cos,
            sin,
        )

    def _process_timbre_encoder_layer_1(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "timbre_encoder",
            1,
            self._apply_timbre_encoder_layers_1_self_attn_q_proj,
            self._apply_timbre_encoder_layers_1_self_attn_k_proj,
            self._apply_timbre_encoder_layers_1_self_attn_v_proj,
            self._apply_timbre_encoder_layers_1_self_attn_o_proj,
            self._apply_timbre_encoder_layers_1_mlp_gate_proj,
            self._apply_timbre_encoder_layers_1_mlp_up_proj,
            self._apply_timbre_encoder_layers_1_mlp_down_proj,
            self._apply_timbre_encoder_layers_1_mlp_act_fn,
            cos,
            sin,
        )

    def _process_timbre_encoder_layer_2(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "timbre_encoder",
            2,
            self._apply_timbre_encoder_layers_2_self_attn_q_proj,
            self._apply_timbre_encoder_layers_2_self_attn_k_proj,
            self._apply_timbre_encoder_layers_2_self_attn_v_proj,
            self._apply_timbre_encoder_layers_2_self_attn_o_proj,
            self._apply_timbre_encoder_layers_2_mlp_gate_proj,
            self._apply_timbre_encoder_layers_2_mlp_up_proj,
            self._apply_timbre_encoder_layers_2_mlp_down_proj,
            self._apply_timbre_encoder_layers_2_mlp_act_fn,
            cos,
            sin,
        )

    def _process_timbre_encoder_layer_3(self, x, cos, sin):
        return self._encoder_layer(
            x,
            "timbre_encoder",
            3,
            self._apply_timbre_encoder_layers_3_self_attn_q_proj,
            self._apply_timbre_encoder_layers_3_self_attn_k_proj,
            self._apply_timbre_encoder_layers_3_self_attn_v_proj,
            self._apply_timbre_encoder_layers_3_self_attn_o_proj,
            self._apply_timbre_encoder_layers_3_mlp_gate_proj,
            self._apply_timbre_encoder_layers_3_mlp_up_proj,
            self._apply_timbre_encoder_layers_3_mlp_down_proj,
            self._apply_timbre_encoder_layers_3_mlp_act_fn,
            cos,
            sin,
        )


def build(device, torch_module):
    return AceStepConditionEncoder(device, torch_module)


_instance = None


def ace_step_condition_encoder(*args, **kwargs):
    global _instance
    if _instance is None:
        model = transformers.AutoModel.from_pretrained(
            HF_MODEL_ID, trust_remote_code=True, torch_dtype="bfloat16", low_cpu_mem_usage=True
        )
        model.eval()
        torch_sub = None
        for path in _CANDIDATE_SUBMODULE_PATHS:
            try:
                torch_sub = _resolve(model, path)
                break
            except (AttributeError, IndexError, KeyError, TypeError):
                continue
        if torch_sub is None:
            raise RuntimeError("partial-stub: could not resolve `ace_step_condition_encoder`")
        _instance = build(ttnn.open_device(device_id=0), torch_sub)
    return _instance(*args, **kwargs)
