# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
#
# SPDX-License-Identifier: Apache-2.0
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
"""Op-level partial TTNN port for `ace_step_audio_tokenizer` of ACE-Step/acestep-v15-base.

Generated deterministically by `tt_hw_planner op-synth`.
Weight loading and op-REUSE/op-ADAPT helpers below are
machine-emitted from the HF reference and DO NOT need LLM
review. The `__call__` implementation falls back to HF
torch so the bring-up smoke test passes immediately;
the LLM's only remaining job is to rewrite `__call__`
to call the pre-bound `_apply_*` helpers in the right
order and fill any op-NEW gaps inline.

Pre-bound deterministic helpers (op palette):
#   self._apply_audio_acoustic_proj(x) -> ttnn.linear  (in=64, out=2048, bias=True)
#   self._apply_attention_pooler_embed_tokens(x) -> ttnn.linear  (in=2048, out=2048, bias=True)
#   self._apply_attention_pooler_layers_0_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_attention_pooler_layers_0_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_attention_pooler_layers_0_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_attention_pooler_layers_0_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_attention_pooler_layers_0_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_attention_pooler_layers_0_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_attention_pooler_layers_0_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_attention_pooler_layers_0_mlp_act_fn(x) -> ttnn.silu
#   self._apply_attention_pooler_layers_1_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_attention_pooler_layers_1_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_attention_pooler_layers_1_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_attention_pooler_layers_1_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_attention_pooler_layers_1_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_attention_pooler_layers_1_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_attention_pooler_layers_1_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_attention_pooler_layers_1_mlp_act_fn(x) -> ttnn.silu
#   self._apply_quantizer_project_in(x) -> ttnn.linear  (in=2048, out=6, bias=True)
#   self._apply_quantizer_project_out(x) -> ttnn.linear  (in=6, out=2048, bias=True)

LLM_GAPs (op-NEW — still need synthesis):
#   - attention_pooler.norm  (Qwen3RMSNorm)
#   - attention_pooler.rotary_emb  (Qwen3RotaryEmbedding)
#   - attention_pooler.layers.0.self_attn.q_norm  (Qwen3RMSNorm)
#   - attention_pooler.layers.0.self_attn.k_norm  (Qwen3RMSNorm)
#   - attention_pooler.layers.0.input_layernorm  (Qwen3RMSNorm)
#   - attention_pooler.layers.0.post_attention_layernorm  (Qwen3RMSNorm)
#   - attention_pooler.layers.1.self_attn.q_norm  (Qwen3RMSNorm)
#   - attention_pooler.layers.1.self_attn.k_norm  (Qwen3RMSNorm)
#   - attention_pooler.layers.1.input_layernorm  (Qwen3RMSNorm)
#   - attention_pooler.layers.1.post_attention_layernorm  (Qwen3RMSNorm)
#   - quantizer.layers.0.project_in  (Identity)
#   - quantizer.layers.0.project_out  (Identity)

HF reference: transformers/src/transformers/models/acestep/modeling_acestep.py
Op counts: total=32  op-REUSE=22  op-ADAPT=0  op-NEW=10"""

from __future__ import annotations

import torch
import transformers

import ttnn

HF_MODEL_ID = "ACE-Step/acestep-v15-base"
_CANDIDATE_SUBMODULE_PATHS = ["tokenizer"]


def _log_runtime_fallback(helper, kind, reason):
    """Append a structured CPU-fallback event for the planner reporter.

    Best-effort; never raises and never blocks the test. Writes to
    `<demo_dir>/_runtime_fallbacks.jsonl` (or the path in env
    TT_HW_PLANNER_RUNTIME_FALLBACK_LOG). The planner truncates this file
    before each pytest invocation and consumes it afterwards.
    """
    try:
        import json as _json
        import os as _os
        import sys as _sys
        import time as _time
        from pathlib import Path as _Path

        _sys.stderr.write("[%s_CPU_FALLBACK] %s: %s\n" % (kind.upper(), helper, reason))
        log_env = _os.environ.get("TT_HW_PLANNER_RUNTIME_FALLBACK_LOG")
        if log_env:
            log_path = _Path(log_env)
        else:
            # _stubs/<safe>.py  ->  demo_dir = parents[1]
            log_path = _Path(__file__).resolve().parents[1] / "_runtime_fallbacks.jsonl"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        ev = {
            "component": _Path(__file__).stem,
            "helper": helper,
            "kind": kind,
            "reason": reason,
            "ts": _time.time(),
        }
        with log_path.open("a") as f:
            f.write(_json.dumps(ev) + "\n")
    except Exception:
        pass


_LLM_GAPS = [
    {"name": "attention_pooler.norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "attention_pooler.rotary_emb", "class": "Qwen3RotaryEmbedding", "notes": ""},
    {"name": "attention_pooler.layers.0.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "attention_pooler.layers.0.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "attention_pooler.layers.0.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "attention_pooler.layers.0.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "attention_pooler.layers.1.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "attention_pooler.layers.1.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "attention_pooler.layers.1.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "attention_pooler.layers.1.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "quantizer.layers.0.project_in", "class": "Identity", "notes": ""},
    {"name": "quantizer.layers.0.project_out", "class": "Identity", "notes": ""},
]


def _resolve(obj, dotted):
    cur = obj
    for tok in dotted.replace("[", ".").replace("]", "").split("."):
        if tok == "":
            continue
        if tok.isdigit():
            cur = cur[int(tok)]
        else:
            cur = getattr(cur, tok)
    return cur


def _coerce_to_torch(x):
    try:
        import ttnn as _ttnn

        if isinstance(x, _ttnn.Tensor):
            import torch as _torch

            t = _ttnn.to_torch(x)
            # Bug Y fix (2026-05-23 live-run sam2-hiera-tiny)
            if t.is_floating_point():
                if t.dtype != _torch.float32:
                    t = t.to(_torch.float32)
            elif t.dtype != _torch.bool:
                t = t.to(_torch.long)
            return t
    except Exception:
        pass
    if isinstance(x, tuple):
        return tuple(_coerce_to_torch(e) for e in x)
    if isinstance(x, list):
        return [_coerce_to_torch(e) for e in x]
    if isinstance(x, dict):
        return {k: _coerce_to_torch(v) for k, v in x.items()}
    return x


class AceStepAudioTokenizer:
    def __init__(self, device, torch_module):
        self.device = device
        self._torch_module = torch_module
        sd = torch_module.state_dict()
        # op-REUSE: audio_acoustic_proj  (Linear 64 -> 2048, bias=True)
        self.w_audio_acoustic_proj_weight = ttnn.from_torch(
            sd["audio_acoustic_proj.weight"].T.contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )
        self.w_audio_acoustic_proj_bias = ttnn.from_torch(
            sd["audio_acoustic_proj.bias"].reshape(1, -1), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # op-REUSE: attention_pooler.embed_tokens  (Linear 2048 -> 2048, bias=True)
        self.w_attention_pooler_embed_tokens_weight = ttnn.from_torch(
            sd["attention_pooler.embed_tokens.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_attention_pooler_embed_tokens_bias = ttnn.from_torch(
            sd["attention_pooler.embed_tokens.bias"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.0.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_attention_pooler_layers_0_self_attn_q_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.0.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_attention_pooler_layers_0_self_attn_k_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.0.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_attention_pooler_layers_0_self_attn_v_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.0.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_attention_pooler_layers_0_self_attn_o_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.0.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_attention_pooler_layers_0_mlp_gate_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.0.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_attention_pooler_layers_0_mlp_up_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.0.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_attention_pooler_layers_0_mlp_down_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.0.mlp.act_fn  (SILU)

        # op-REUSE: attention_pooler.layers.1.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_attention_pooler_layers_1_self_attn_q_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.1.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_attention_pooler_layers_1_self_attn_k_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.1.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_attention_pooler_layers_1_self_attn_v_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.1.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_attention_pooler_layers_1_self_attn_o_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.1.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_attention_pooler_layers_1_mlp_gate_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.1.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_attention_pooler_layers_1_mlp_up_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.1.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_attention_pooler_layers_1_mlp_down_proj_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: attention_pooler.layers.1.mlp.act_fn  (SILU)

        # op-REUSE: quantizer.project_in  (Linear 2048 -> 6, bias=True)
        self.w_quantizer_project_in_weight = ttnn.from_torch(
            sd["quantizer.project_in.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_quantizer_project_in_bias = ttnn.from_torch(
            sd["quantizer.project_in.bias"].reshape(1, -1), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # op-REUSE: quantizer.project_out  (Linear 6 -> 2048, bias=True)
        self.w_quantizer_project_out_weight = ttnn.from_torch(
            sd["quantizer.project_out.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_quantizer_project_out_bias = ttnn.from_torch(
            sd["quantizer.project_out.bias"].reshape(1, -1), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # op-NEW: RMSNorm weights
        self.w_attention_pooler_norm_weight = ttnn.from_torch(
            sd["attention_pooler.norm.weight"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_attention_pooler_layers_0_input_layernorm_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.input_layernorm.weight"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_attention_pooler_layers_0_self_attn_q_norm_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.self_attn.q_norm.weight"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_attention_pooler_layers_0_self_attn_k_norm_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.self_attn.k_norm.weight"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_attention_pooler_layers_0_post_attention_layernorm_weight = ttnn.from_torch(
            sd["attention_pooler.layers.0.post_attention_layernorm.weight"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_attention_pooler_layers_1_input_layernorm_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.input_layernorm.weight"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_attention_pooler_layers_1_self_attn_q_norm_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.self_attn.q_norm.weight"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_attention_pooler_layers_1_self_attn_k_norm_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.self_attn.k_norm.weight"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_attention_pooler_layers_1_post_attention_layernorm_weight = ttnn.from_torch(
            sd["attention_pooler.layers.1.post_attention_layernorm.weight"].reshape(1, -1),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-NEW: Precompute rotary embeddings
        # q_proj outputs 2048 dims with 16 heads, so head_dim = 2048 / 16 = 128
        rope_dim = 128
        rope_base = 10000.0
        seq_len = 10

        inv_freq = 1.0 / (rope_base ** (torch.arange(0, rope_dim, 2, dtype=torch.float32) / rope_dim))
        t = torch.arange(seq_len, dtype=torch.float32)
        freqs = torch.einsum("i,j->ij", t, inv_freq)
        freqs = torch.cat([freqs, freqs], dim=-1)
        cos_vals = freqs.cos()[None, None, :, :]
        sin_vals = freqs.sin()[None, None, :, :]

        self.w_rotary_cos = ttnn.from_torch(
            cos_vals.to(torch.bfloat16), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )
        self.w_rotary_sin = ttnn.from_torch(
            sin_vals.to(torch.bfloat16), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # op-NEW (added): the block above precomputes RoPE tables for the WRONG
        # geometry (seq_len=10, base=10000) -- this module's actual attention runs
        # over S = pool_window_size + 1 = 6 positions (P patches + 1 prepended
        # special/CLS token) with rope_theta = 1e6 (see config below), so __call__
        # rebuilds correct cos/sin tables on the fly via `_compute_rope_cos_sin`
        # instead of using w_rotary_cos/w_rotary_sin. Kept the original (unused)
        # buffers above untouched to minimize the __init__ diff.

        # op-NEW: special_token (CLS-like pooling token), prepended to the P
        # patches before the attention_pooler's transformer layers run. Not part
        # of the op-classifier's Linear/Norm palette (it's a bare nn.Parameter),
        # so it's loaded here the same way as every other weight -- a plain
        # state_dict tensor materialized onto device, no forward-path computation.
        self.w_attention_pooler_special_token = ttnn.from_torch(
            sd["attention_pooler.special_token"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-NEW: FSQ quantization constants (symmetry-preserving bound + hard
        # clamp), derived from the (non-persistent-buffer) integer `levels` on
        # the underlying vector_quantize_pytorch FSQ layer. These are fixed
        # per-codebook-dim constants, not functions of the input, so they are
        # materialized once here exactly like every other constant weight.
        fsq_layer = torch_module.quantizer.layers[0]
        _levels = fsq_layer._levels.detach().to(torch.float32).reshape(1, 1, -1)
        _basis = fsq_layer._basis.detach().to(torch.float32).reshape(1, 1, -1)
        _a = (_levels - 1.0) / 2.0
        _b = _a + 0.5
        _s = 2.0 / (_levels - 1.0)
        self.w_fsq_a = ttnn.from_torch(_a, dtype=ttnn.float32, layout=ttnn.TILE_LAYOUT, device=device)
        self.w_fsq_b = ttnn.from_torch(_b, dtype=ttnn.float32, layout=ttnn.TILE_LAYOUT, device=device)
        self.w_fsq_s = ttnn.from_torch(_s, dtype=ttnn.float32, layout=ttnn.TILE_LAYOUT, device=device)
        self.w_fsq_basis = ttnn.from_torch(_basis, dtype=ttnn.float32, layout=ttnn.TILE_LAYOUT, device=device)

        # Attention geometry / RoPE base for the attention_pooler's Qwen3-style
        # layers (config.num_attention_heads=16, num_key_value_heads=8,
        # head_dim=128, rope_theta=1e6 for this model).
        cfg = torch_module.config
        self._num_attention_heads = cfg.num_attention_heads
        self._num_key_value_heads = cfg.num_key_value_heads
        self._head_dim = getattr(cfg, "head_dim", cfg.hidden_size // cfg.num_attention_heads)
        self._rope_theta = cfg.rope_theta

    def _apply_audio_acoustic_proj(self, x):
        return ttnn.linear(x, self.w_audio_acoustic_proj_weight, bias=self.w_audio_acoustic_proj_bias)

    def _apply_attention_pooler_embed_tokens(self, x):
        return ttnn.linear(
            x, self.w_attention_pooler_embed_tokens_weight, bias=self.w_attention_pooler_embed_tokens_bias
        )

    def _apply_attention_pooler_layers_0_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_0_self_attn_q_proj_weight)

    def _apply_attention_pooler_layers_0_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_0_self_attn_k_proj_weight)

    def _apply_attention_pooler_layers_0_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_0_self_attn_v_proj_weight)

    def _apply_attention_pooler_layers_0_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_0_self_attn_o_proj_weight)

    def _apply_attention_pooler_layers_0_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_0_mlp_gate_proj_weight)

    def _apply_attention_pooler_layers_0_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_0_mlp_up_proj_weight)

    def _apply_attention_pooler_layers_0_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_0_mlp_down_proj_weight)

    def _apply_attention_pooler_layers_0_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_attention_pooler_layers_1_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_1_self_attn_q_proj_weight)

    def _apply_attention_pooler_layers_1_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_1_self_attn_k_proj_weight)

    def _apply_attention_pooler_layers_1_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_1_self_attn_v_proj_weight)

    def _apply_attention_pooler_layers_1_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_1_self_attn_o_proj_weight)

    def _apply_attention_pooler_layers_1_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_1_mlp_gate_proj_weight)

    def _apply_attention_pooler_layers_1_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_1_mlp_up_proj_weight)

    def _apply_attention_pooler_layers_1_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_attention_pooler_layers_1_mlp_down_proj_weight)

    def _apply_attention_pooler_layers_1_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_quantizer_project_in(self, x):
        return ttnn.linear(x, self.w_quantizer_project_in_weight, bias=self.w_quantizer_project_in_bias)

    def _apply_quantizer_project_out(self, x):
        return ttnn.linear(x, self.w_quantizer_project_out_weight, bias=self.w_quantizer_project_out_bias)

    def _apply_rms_norm(self, x, weight, eps=1e-6):
        x_sq = ttnn.mul(x, x)
        mean_sq = ttnn.mean(x_sq, dim=-1, keepdim=True)
        mean_sq_eps = ttnn.add(mean_sq, eps)
        rms = ttnn.sqrt(mean_sq_eps)
        rms_inv = ttnn.reciprocal(rms)
        normalized = ttnn.mul(x, rms_inv)
        return ttnn.mul(normalized, weight)

    # ---- op-NEW: RoPE (Qwen3RotaryEmbedding + apply_rotary_pos_emb) ----
    def _compute_rope_cos_sin(self, seq_len, head_dim):
        inv_freq = 1.0 / (self._rope_theta ** (torch.arange(0, head_dim, 2, dtype=torch.float32) / head_dim))
        positions = torch.arange(seq_len, dtype=torch.float32)
        freqs = torch.outer(positions, inv_freq)
        emb = torch.cat([freqs, freqs], dim=-1)
        cos = emb.cos().reshape(1, 1, seq_len, head_dim)
        sin = emb.sin().reshape(1, 1, seq_len, head_dim)
        cos_t = ttnn.from_torch(
            cos.to(torch.bfloat16), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device
        )
        sin_t = ttnn.from_torch(
            sin.to(torch.bfloat16), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device
        )
        return cos_t, sin_t

    def _rotate_half(self, x, head_dim):
        half = head_dim // 2
        x1 = x[..., :half]
        x2 = x[..., half:]
        return ttnn.concat([ttnn.neg(x2), x1], dim=-1)

    def _apply_rope(self, x, cos, sin, head_dim):
        return ttnn.add(ttnn.mul(x, cos), ttnn.mul(self._rotate_half(x, head_dim), sin))

    def __call__(self, hidden_states):
        # hidden_states: (B, T, P, D_in) where P = pool_window_size (5) and
        # D_in = audio_acoustic_hidden_dim (64).
        B, T, P, D_in = tuple(hidden_states.shape)
        hidden_size = 2048
        num_heads = self._num_attention_heads
        num_kv_heads = self._num_key_value_heads
        head_dim = self._head_dim
        n_rep = num_heads // num_kv_heads
        scaling = head_dim**-0.5

        # ---- audio_acoustic_proj: 64 -> 2048, elementwise over (B,T,P) ----
        x = ttnn.reshape(hidden_states, (B * T * P, D_in))
        x = self._apply_audio_acoustic_proj(x)

        BT = B * T
        x = ttnn.reshape(x, (BT, P, hidden_size))

        # ---- attention_pooler: embed patches, prepend CLS-like special token ----
        x = self._apply_attention_pooler_embed_tokens(x)

        special = ttnn.repeat(self.w_attention_pooler_special_token, ttnn.Shape([BT, 1, 1]))
        x = ttnn.concat([special, x], dim=1)
        S = P + 1

        # Shared rotary tables for this forward pass (identical across layers).
        # cos/sin come out (1, 1, S, head_dim); replicate across the head dim so
        # the elementwise RoPE mul/add broadcasts cleanly.
        cos, sin = self._compute_rope_cos_sin(S, head_dim)
        cos_q = ttnn.repeat(cos, ttnn.Shape([1, num_heads, 1, 1]))
        sin_q = ttnn.repeat(sin, ttnn.Shape([1, num_heads, 1, 1]))
        cos_k = ttnn.repeat(cos, ttnn.Shape([1, num_kv_heads, 1, 1]))
        sin_k = ttnn.repeat(sin, ttnn.Shape([1, num_kv_heads, 1, 1]))

        # q_norm/k_norm are RMSNorm applied per-head (on head_dim), so reshape
        # their (1, hidden_size)-flattened weights down to (1, 1, 1, head_dim)
        # once up front instead of relying on cross-rank broadcasting.
        q_norm_w = [
            ttnn.reshape(self.w_attention_pooler_layers_0_self_attn_q_norm_weight, (1, 1, 1, head_dim)),
            ttnn.reshape(self.w_attention_pooler_layers_1_self_attn_q_norm_weight, (1, 1, 1, head_dim)),
        ]
        k_norm_w = [
            ttnn.reshape(self.w_attention_pooler_layers_0_self_attn_k_norm_weight, (1, 1, 1, head_dim)),
            ttnn.reshape(self.w_attention_pooler_layers_1_self_attn_k_norm_weight, (1, 1, 1, head_dim)),
        ]

        layer_helpers = [
            (
                self.w_attention_pooler_layers_0_input_layernorm_weight,
                self._apply_attention_pooler_layers_0_self_attn_q_proj,
                self._apply_attention_pooler_layers_0_self_attn_k_proj,
                self._apply_attention_pooler_layers_0_self_attn_v_proj,
                q_norm_w[0],
                k_norm_w[0],
                self._apply_attention_pooler_layers_0_self_attn_o_proj,
                self.w_attention_pooler_layers_0_post_attention_layernorm_weight,
                self._apply_attention_pooler_layers_0_mlp_gate_proj,
                self._apply_attention_pooler_layers_0_mlp_up_proj,
                self._apply_attention_pooler_layers_0_mlp_down_proj,
                self._apply_attention_pooler_layers_0_mlp_act_fn,
            ),
            (
                self.w_attention_pooler_layers_1_input_layernorm_weight,
                self._apply_attention_pooler_layers_1_self_attn_q_proj,
                self._apply_attention_pooler_layers_1_self_attn_k_proj,
                self._apply_attention_pooler_layers_1_self_attn_v_proj,
                q_norm_w[1],
                k_norm_w[1],
                self._apply_attention_pooler_layers_1_self_attn_o_proj,
                self.w_attention_pooler_layers_1_post_attention_layernorm_weight,
                self._apply_attention_pooler_layers_1_mlp_gate_proj,
                self._apply_attention_pooler_layers_1_mlp_up_proj,
                self._apply_attention_pooler_layers_1_mlp_down_proj,
                self._apply_attention_pooler_layers_1_mlp_act_fn,
            ),
        ]

        for (
            input_ln_w,
            q_proj,
            k_proj,
            v_proj,
            q_norm_weight,
            k_norm_weight,
            o_proj,
            post_ln_w,
            gate_proj,
            up_proj,
            down_proj,
            act_fn,
        ) in layer_helpers:
            residual = x
            h = self._apply_rms_norm(x, input_ln_w)

            # Qwen3-style attention: q_norm/k_norm are applied per-head (on
            # head_dim, AFTER splitting heads, BEFORE the (1,2) transpose).
            q = ttnn.reshape(q_proj(h), (BT, S, num_heads, head_dim))
            q = self._apply_rms_norm(q, q_norm_weight)
            q = ttnn.transpose(q, 1, 2)  # (BT, num_heads, S, head_dim)

            k = ttnn.reshape(k_proj(h), (BT, S, num_kv_heads, head_dim))
            k = self._apply_rms_norm(k, k_norm_weight)
            k = ttnn.transpose(k, 1, 2)  # (BT, num_kv_heads, S, head_dim)

            v = ttnn.reshape(v_proj(h), (BT, S, num_kv_heads, head_dim))
            v = ttnn.transpose(v, 1, 2)  # (BT, num_kv_heads, S, head_dim)

            q = self._apply_rope(q, cos_q, sin_q, head_dim)
            k = self._apply_rope(k, cos_k, sin_k, head_dim)

            # GQA: expand KV heads to match query heads (repeat_kv ==
            # repeat_interleave along the head dim).
            if n_rep > 1:
                k = ttnn.repeat_interleave(k, n_rep, dim=1)
                v = ttnn.repeat_interleave(v, n_rep, dim=1)

            # Bidirectional (non-causal) attention. S = pool_window_size + 1 = 6
            # is far smaller than sliding_window (128), so the sliding-window
            # mask is a no-op and there is no padding mask.
            attn_weights = ttnn.matmul(q, ttnn.transpose(k, 2, 3))  # (BT, num_heads, S, S)
            attn_weights = ttnn.mul(attn_weights, scaling)
            attn_weights = ttnn.softmax(attn_weights, dim=-1)

            attn_out = ttnn.matmul(attn_weights, v)  # (BT, num_heads, S, head_dim)
            attn_out = ttnn.transpose(attn_out, 1, 2)  # (BT, S, num_heads, head_dim)
            attn_out = ttnn.reshape(attn_out, (BT, S, num_heads * head_dim))
            attn_out = o_proj(attn_out)

            x = ttnn.add(residual, attn_out)

            # Qwen3MLP: down_proj(silu(gate_proj(x)) * up_proj(x))
            residual = x
            h = self._apply_rms_norm(x, post_ln_w)
            gate = act_fn(gate_proj(h))
            up = up_proj(h)
            mlp_out = down_proj(ttnn.mul(gate, up))
            x = ttnn.add(residual, mlp_out)

        x = self._apply_rms_norm(x, self.w_attention_pooler_norm_weight)

        # Extract the special (CLS) token output at position 0 -> pooled representation.
        cls = x[:, 0:1, :]
        pooled = ttnn.reshape(cls, (B, T, hidden_size))

        # ---- quantizer: ResidualFSQ (project_in -> FSQ -> project_out) ----
        z = self._apply_quantizer_project_in(pooled)

        # FSQ quantization (symmetry-preserving bound with hard clamp). Do the
        # arithmetic in float32 to match HF reference and prevent bf16 rounding
        # from crossing floor() decision boundaries.
        z = ttnn.typecast(z, ttnn.float32)
        c = ttnn.clamp(z, -1.0, 1.0)

        # bracket = floor((L-1)*(c+1)/2 + 0.5) = floor(a*c + b)
        bracket = ttnn.multiply(c, self.w_fsq_a)
        bracket = ttnn.add(bracket, self.w_fsq_b)
        bracket = ttnn.floor(bracket)

        # codes = (2/(L-1)) * bracket - 1 = s*bracket - 1
        codes = ttnn.multiply(bracket, self.w_fsq_s)
        codes = ttnn.subtract(codes, 1.0)

        # indices = round(sum over last dim of bracket * basis) -> (B, T, 1)
        weighted = ttnn.multiply(bracket, self.w_fsq_basis)
        idx = ttnn.sum(weighted, dim=-1)
        idx = ttnn.round(idx)
        idx = ttnn.typecast(idx, ttnn.int32)
        idx = ttnn.unsqueeze(idx, dim=-1)

        quantized = self._apply_quantizer_project_out(codes)

        return quantized, idx


def build(device, torch_module):
    return AceStepAudioTokenizer(device, torch_module)


_instance = None


def ace_step_audio_tokenizer(*args, **kwargs):
    global _instance
    if _instance is None:
        model = transformers.AutoModel.from_pretrained(
            HF_MODEL_ID, trust_remote_code=True, torch_dtype="bfloat16", low_cpu_mem_usage=True
        )
        model.eval()
        torch_sub = None
        for path in _CANDIDATE_SUBMODULE_PATHS:
            try:
                torch_sub = _resolve(model, path)
                break
            except (AttributeError, IndexError, KeyError, TypeError):
                continue
        if torch_sub is None:
            raise RuntimeError("partial-stub: could not resolve `ace_step_audio_tokenizer`")
        _instance = build(ttnn.open_device(device_id=0), torch_sub)
    return _instance(*args, **kwargs)
