# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
#
# SPDX-License-Identifier: Apache-2.0
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
"""Op-level partial TTNN port for `attention_pooler` of ACE-Step/acestep-v15-base.

Generated deterministically by `tt_hw_planner op-synth`.
Weight loading and op-REUSE/op-ADAPT helpers below are
machine-emitted from the HF reference and DO NOT need LLM
review. The `__call__` implementation falls back to HF
torch so the bring-up smoke test passes immediately;
the LLM's only remaining job is to rewrite `__call__`
to call the pre-bound `_apply_*` helpers in the right
order and fill any op-NEW gaps inline.

Pre-bound deterministic helpers (op palette):
#   self._apply_embed_tokens(x) -> ttnn.linear  (in=2048, out=2048, bias=True)
#   self._apply_layers_0_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_layers_0_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_layers_0_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_layers_0_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_layers_0_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_layers_0_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_layers_0_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_layers_0_mlp_act_fn(x) -> ttnn.silu
#   self._apply_layers_1_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_layers_1_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_layers_1_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_layers_1_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_layers_1_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_layers_1_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_layers_1_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_layers_1_mlp_act_fn(x) -> ttnn.silu

LLM_GAPs (op-NEW — still need synthesis):
#   - norm  (Qwen3RMSNorm)
#   - rotary_emb  (Qwen3RotaryEmbedding)
#   - layers.0.self_attn.q_norm  (Qwen3RMSNorm)
#   - layers.0.self_attn.k_norm  (Qwen3RMSNorm)
#   - layers.0.input_layernorm  (Qwen3RMSNorm)
#   - layers.0.post_attention_layernorm  (Qwen3RMSNorm)
#   - layers.1.self_attn.q_norm  (Qwen3RMSNorm)
#   - layers.1.self_attn.k_norm  (Qwen3RMSNorm)
#   - layers.1.input_layernorm  (Qwen3RMSNorm)
#   - layers.1.post_attention_layernorm  (Qwen3RMSNorm)

HF reference: transformers/src/transformers/models/acestep/modeling_acestep.py
Op counts: total=27  op-REUSE=17  op-ADAPT=0  op-NEW=10"""

from __future__ import annotations

import torch
import transformers

import ttnn

HF_MODEL_ID = "ACE-Step/acestep-v15-base"
_CANDIDATE_SUBMODULE_PATHS = ["tokenizer.attention_pooler"]


def _log_runtime_fallback(helper, kind, reason):
    """Append a structured CPU-fallback event for the planner reporter.

    Best-effort; never raises and never blocks the test. Writes to
    `<demo_dir>/_runtime_fallbacks.jsonl` (or the path in env
    TT_HW_PLANNER_RUNTIME_FALLBACK_LOG). The planner truncates this file
    before each pytest invocation and consumes it afterwards.
    """
    try:
        import json as _json
        import os as _os
        import sys as _sys
        import time as _time
        from pathlib import Path as _Path

        _sys.stderr.write("[%s_CPU_FALLBACK] %s: %s\n" % (kind.upper(), helper, reason))
        log_env = _os.environ.get("TT_HW_PLANNER_RUNTIME_FALLBACK_LOG")
        if log_env:
            log_path = _Path(log_env)
        else:
            # _stubs/<safe>.py  ->  demo_dir = parents[1]
            log_path = _Path(__file__).resolve().parents[1] / "_runtime_fallbacks.jsonl"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        ev = {
            "component": _Path(__file__).stem,
            "helper": helper,
            "kind": kind,
            "reason": reason,
            "ts": _time.time(),
        }
        with log_path.open("a") as f:
            f.write(_json.dumps(ev) + "\n")
    except Exception:
        pass


_LLM_GAPS = [
    {"name": "norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "rotary_emb", "class": "Qwen3RotaryEmbedding", "notes": ""},
    {"name": "layers.0.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.0.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.0.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.0.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.1.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.1.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.1.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.1.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
]


def _resolve(obj, dotted):
    cur = obj
    for tok in dotted.replace("[", ".").replace("]", "").split("."):
        if tok == "":
            continue
        if tok.isdigit():
            cur = cur[int(tok)]
        else:
            cur = getattr(cur, tok)
    return cur


def _coerce_to_torch(x):
    try:
        import ttnn as _ttnn

        if isinstance(x, _ttnn.Tensor):
            import torch as _torch

            t = _ttnn.to_torch(x)
            # Bug Y fix (2026-05-23 live-run sam2-hiera-tiny)
            if t.is_floating_point():
                if t.dtype != _torch.float32:
                    t = t.to(_torch.float32)
            elif t.dtype != _torch.bool:
                t = t.to(_torch.long)
            return t
    except Exception:
        pass
    if isinstance(x, tuple):
        return tuple(_coerce_to_torch(e) for e in x)
    if isinstance(x, list):
        return [_coerce_to_torch(e) for e in x]
    if isinstance(x, dict):
        return {k: _coerce_to_torch(v) for k, v in x.items()}
    return x


class AttentionPooler:
    def __init__(self, device, torch_module):
        self.device = device
        self._torch_module = torch_module
        sd = torch_module.state_dict()
        # op-REUSE: embed_tokens  (Linear 2048 -> 2048, bias=True)
        self.w_embed_tokens_weight = ttnn.from_torch(
            sd["embed_tokens.weight"].T.contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )
        self.w_embed_tokens_bias = ttnn.from_torch(
            sd["embed_tokens.bias"].reshape(1, -1), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # op-REUSE: layers.0.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_layers_0_self_attn_q_proj_weight = ttnn.from_torch(
            sd["layers.0.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_layers_0_self_attn_k_proj_weight = ttnn.from_torch(
            sd["layers.0.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_layers_0_self_attn_v_proj_weight = ttnn.from_torch(
            sd["layers.0.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_layers_0_self_attn_o_proj_weight = ttnn.from_torch(
            sd["layers.0.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_layers_0_mlp_gate_proj_weight = ttnn.from_torch(
            sd["layers.0.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_layers_0_mlp_up_proj_weight = ttnn.from_torch(
            sd["layers.0.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_layers_0_mlp_down_proj_weight = ttnn.from_torch(
            sd["layers.0.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.mlp.act_fn  (SILU)

        # op-REUSE: layers.1.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_layers_1_self_attn_q_proj_weight = ttnn.from_torch(
            sd["layers.1.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_layers_1_self_attn_k_proj_weight = ttnn.from_torch(
            sd["layers.1.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_layers_1_self_attn_v_proj_weight = ttnn.from_torch(
            sd["layers.1.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_layers_1_self_attn_o_proj_weight = ttnn.from_torch(
            sd["layers.1.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_layers_1_mlp_gate_proj_weight = ttnn.from_torch(
            sd["layers.1.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_layers_1_mlp_up_proj_weight = ttnn.from_torch(
            sd["layers.1.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_layers_1_mlp_down_proj_weight = ttnn.from_torch(
            sd["layers.1.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.mlp.act_fn  (SILU)

        # op-NEW: RMSNorm weights
        self.w_norm_weight = ttnn.from_torch(
            sd["norm.weight"].contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )
        self.w_layers_0_self_attn_q_norm_weight = ttnn.from_torch(
            sd["layers.0.self_attn.q_norm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_0_self_attn_k_norm_weight = ttnn.from_torch(
            sd["layers.0.self_attn.k_norm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_0_input_layernorm_weight = ttnn.from_torch(
            sd["layers.0.input_layernorm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_0_post_attention_layernorm_weight = ttnn.from_torch(
            sd["layers.0.post_attention_layernorm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_1_self_attn_q_norm_weight = ttnn.from_torch(
            sd["layers.1.self_attn.q_norm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_1_self_attn_k_norm_weight = ttnn.from_torch(
            sd["layers.1.self_attn.k_norm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_1_input_layernorm_weight = ttnn.from_torch(
            sd["layers.1.input_layernorm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_1_post_attention_layernorm_weight = ttnn.from_torch(
            sd["layers.1.post_attention_layernorm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # RMS norm epsilon
        self._eps = torch_module.config.rms_norm_eps

        # op-NEW: "special_token" nn.Parameter (1, 1, hidden_size) — CLS-like pooling token,
        # prepended to the patch sequence before the encoder layers. Not part of the
        # op-classifier's Linear/Norm palette, so it was missing from the original weight
        # dump; loaded here the same way as every other op-REUSE/op-NEW weight (a plain
        # state_dict tensor materialized onto device, no forward-path computation).
        self.w_special_token = ttnn.from_torch(
            sd["special_token"].contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # Attention geometry needed to wire q_norm/k_norm (per-head, not per-hidden-dim)
        # and RoPE together correctly.
        cfg = torch_module.config
        self._num_attention_heads = cfg.num_attention_heads
        self._num_key_value_heads = cfg.num_key_value_heads
        self._head_dim = getattr(cfg, "head_dim", cfg.hidden_size // cfg.num_attention_heads)
        self._rope_theta = cfg.rope_theta

    def _apply_embed_tokens(self, x):
        return ttnn.linear(x, self.w_embed_tokens_weight, bias=self.w_embed_tokens_bias)

    def _apply_layers_0_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_self_attn_q_proj_weight)

    def _apply_layers_0_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_self_attn_k_proj_weight)

    def _apply_layers_0_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_self_attn_v_proj_weight)

    def _apply_layers_0_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_self_attn_o_proj_weight)

    def _apply_layers_0_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_mlp_gate_proj_weight)

    def _apply_layers_0_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_mlp_up_proj_weight)

    def _apply_layers_0_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_mlp_down_proj_weight)

    def _apply_layers_0_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_layers_1_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_self_attn_q_proj_weight)

    def _apply_layers_1_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_self_attn_k_proj_weight)

    def _apply_layers_1_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_self_attn_v_proj_weight)

    def _apply_layers_1_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_self_attn_o_proj_weight)

    def _apply_layers_1_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_mlp_gate_proj_weight)

    def _apply_layers_1_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_mlp_up_proj_weight)

    def _apply_layers_1_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_mlp_down_proj_weight)

    def _apply_layers_1_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_norm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_norm_weight)

    def _apply_layers_0_self_attn_q_norm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_0_self_attn_q_norm_weight)

    def _apply_layers_0_self_attn_k_norm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_0_self_attn_k_norm_weight)

    def _apply_layers_0_input_layernorm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_0_input_layernorm_weight)

    def _apply_layers_0_post_attention_layernorm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_0_post_attention_layernorm_weight)

    def _apply_layers_1_self_attn_q_norm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_1_self_attn_q_norm_weight)

    def _apply_layers_1_self_attn_k_norm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_1_self_attn_k_norm_weight)

    def _apply_layers_1_input_layernorm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_1_input_layernorm_weight)

    def _apply_layers_1_post_attention_layernorm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_1_post_attention_layernorm_weight)

    # ---- op-NEW: RoPE (Qwen3RotaryEmbedding + apply_rotary_pos_emb) ----
    def _compute_rope_cos_sin(self, seq_len):
        # Position embeddings are a fixed function of (seq_len, head_dim, rope_theta) —
        # not of the input tensor's values — so building the table with torch on the
        # host and shipping it to device via ttnn.from_torch is just weight loading,
        # exactly like every other constant tensor in __init__; the actual forward
        # math (mul/add against q/k) all happens on-device in ttnn.
        head_dim = self._head_dim
        inv_freq = 1.0 / (self._rope_theta ** (torch.arange(0, head_dim, 2, dtype=torch.float32) / head_dim))
        positions = torch.arange(seq_len, dtype=torch.float32)
        freqs = torch.outer(positions, inv_freq)
        emb = torch.cat([freqs, freqs], dim=-1)
        cos = emb.cos().reshape(1, 1, seq_len, head_dim)
        sin = emb.sin().reshape(1, 1, seq_len, head_dim)
        cos_t = ttnn.from_torch(cos, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device)
        sin_t = ttnn.from_torch(sin, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device)
        return cos_t, sin_t

    def _rotate_half(self, x, head_dim):
        half = head_dim // 2
        x1 = x[..., :half]
        x2 = x[..., half:]
        return ttnn.concat([ttnn.neg(x2), x1], dim=-1)

    def _apply_rope(self, x, cos, sin, head_dim):
        return ttnn.add(ttnn.mul(x, cos), ttnn.mul(self._rotate_half(x, head_dim), sin))

    def __call__(self, hidden_states):
        if not isinstance(hidden_states, ttnn.Tensor):
            hidden_states = ttnn.from_torch(
                hidden_states, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=self.device
            )

        # x: (B, T, P, D) -- B*T independent "sequences" of P patches, pooled via a
        # prepended special (CLS-like) token attended to across P+1 positions.
        B, T, P, D = tuple(hidden_states.shape)
        BT = B * T
        num_heads = self._num_attention_heads
        num_kv_heads = self._num_key_value_heads
        head_dim = self._head_dim
        n_rep = num_heads // num_kv_heads
        scaling = head_dim**-0.5

        # HF reference order: embed_tokens(x) FIRST over the P patches, THEN prepend the
        # (un-embedded) special token, THEN rearrange (b t) p c. Flattening (B,T)->BT up
        # front is equivalent because the Linear and the broadcast special token act
        # independently on each (b,t) slice.
        x = ttnn.reshape(hidden_states, (BT, P, D))
        x = self._apply_embed_tokens(x)

        special = ttnn.repeat(self.w_special_token, ttnn.Shape([BT, 1, 1]))
        x = ttnn.concat([special, x], dim=1)

        S = P + 1

        # Shared rotary tables — identical across every (b,t) sequence and every layer.
        # cos/sin come out (1, 1, S, head_dim); materialize them across the head dim so
        # the elementwise RoPE mul/add broadcasts cleanly (only dim0 batch broadcast
        # remains, which ttnn binary ops handle reliably).
        cos, sin = self._compute_rope_cos_sin(S)
        cos_q = ttnn.repeat(cos, ttnn.Shape([1, num_heads, 1, 1]))
        sin_q = ttnn.repeat(sin, ttnn.Shape([1, num_heads, 1, 1]))
        cos_k = ttnn.repeat(cos, ttnn.Shape([1, num_kv_heads, 1, 1]))
        sin_k = ttnn.repeat(sin, ttnn.Shape([1, num_kv_heads, 1, 1]))

        layer_helpers = [
            (
                self._apply_layers_0_input_layernorm,
                self._apply_layers_0_self_attn_q_proj,
                self._apply_layers_0_self_attn_k_proj,
                self._apply_layers_0_self_attn_v_proj,
                self._apply_layers_0_self_attn_q_norm,
                self._apply_layers_0_self_attn_k_norm,
                self._apply_layers_0_self_attn_o_proj,
                self._apply_layers_0_post_attention_layernorm,
                self._apply_layers_0_mlp_gate_proj,
                self._apply_layers_0_mlp_up_proj,
                self._apply_layers_0_mlp_down_proj,
                self._apply_layers_0_mlp_act_fn,
            ),
            (
                self._apply_layers_1_input_layernorm,
                self._apply_layers_1_self_attn_q_proj,
                self._apply_layers_1_self_attn_k_proj,
                self._apply_layers_1_self_attn_v_proj,
                self._apply_layers_1_self_attn_q_norm,
                self._apply_layers_1_self_attn_k_norm,
                self._apply_layers_1_self_attn_o_proj,
                self._apply_layers_1_post_attention_layernorm,
                self._apply_layers_1_mlp_gate_proj,
                self._apply_layers_1_mlp_up_proj,
                self._apply_layers_1_mlp_down_proj,
                self._apply_layers_1_mlp_act_fn,
            ),
        ]

        for (
            input_ln,
            q_proj,
            k_proj,
            v_proj,
            q_norm,
            k_norm,
            o_proj,
            post_ln,
            gate_proj,
            up_proj,
            down_proj,
            act_fn,
        ) in layer_helpers:
            residual = x
            h = input_ln(x)

            # Qwen3-style attention: q_norm/k_norm are applied per-head (on head_dim,
            # AFTER splitting heads, BEFORE the (1,2) transpose) -- not on the full
            # hidden dim.
            q = ttnn.reshape(q_proj(h), (BT, S, num_heads, head_dim))
            q = q_norm(q)
            q = ttnn.transpose(q, 1, 2)  # (BT, num_heads, S, head_dim)

            k = ttnn.reshape(k_proj(h), (BT, S, num_kv_heads, head_dim))
            k = k_norm(k)
            k = ttnn.transpose(k, 1, 2)  # (BT, num_kv_heads, S, head_dim)

            v = ttnn.reshape(v_proj(h), (BT, S, num_kv_heads, head_dim))
            v = ttnn.transpose(v, 1, 2)  # (BT, num_kv_heads, S, head_dim)

            q = self._apply_rope(q, cos_q, sin_q, head_dim)
            k = self._apply_rope(k, cos_k, sin_k, head_dim)

            # GQA: expand KV heads to match query heads (repeat_kv == repeat_interleave
            # along the head dim). ttnn SDPA does NOT auto-broadcast 8 kv-heads to 16
            # q-heads, so do the manual matmul-softmax-matmul path exactly like the
            # graduated AceStepEncoderLayer port.
            if n_rep > 1:
                k = ttnn.repeat_interleave(k, n_rep, dim=1)
                v = ttnn.repeat_interleave(v, n_rep, dim=1)

            # Bidirectional (non-causal) attention. S (= pool_window_size + 1 = 6) is far
            # smaller than sliding_window (128), so the sliding-window mask is a no-op and
            # there is no padding mask -> no additive mask term.
            attn_weights = ttnn.matmul(q, ttnn.transpose(k, 2, 3))  # (BT, num_heads, S, S)
            attn_weights = ttnn.mul(attn_weights, scaling)
            attn_weights = ttnn.softmax(attn_weights, dim=-1)

            attn_out = ttnn.matmul(attn_weights, v)  # (BT, num_heads, S, head_dim)
            attn_out = ttnn.transpose(attn_out, 1, 2)  # (BT, S, num_heads, head_dim)
            attn_out = ttnn.reshape(attn_out, (BT, S, num_heads * head_dim))
            attn_out = o_proj(attn_out)

            x = ttnn.add(residual, attn_out)

            # Qwen3MLP: down_proj(silu(gate_proj(x)) * up_proj(x)) -- silu on the GATE
            # branch only, THEN elementwise-mul with up (not silu(gate*up)).
            residual = x
            h = post_ln(x)
            gate = act_fn(gate_proj(h))
            up = up_proj(h)
            mlp_out = down_proj(ttnn.mul(gate, up))
            x = ttnn.add(residual, mlp_out)

        x = self._apply_norm(x)

        # Extract the special (CLS) token output at position 0 -> pooled representation.
        cls = x[:, 0:1, :]
        out = ttnn.reshape(cls, (B, T, D))
        return out


def build(device, torch_module):
    return AttentionPooler(device, torch_module)


_instance = None


def attention_pooler(*args, **kwargs):
    global _instance
    if _instance is None:
        model = transformers.AutoModel.from_pretrained(
            HF_MODEL_ID, trust_remote_code=True, torch_dtype="bfloat16", low_cpu_mem_usage=True
        )
        model.eval()
        torch_sub = None
        for path in _CANDIDATE_SUBMODULE_PATHS:
            try:
                torch_sub = _resolve(model, path)
                break
            except (AttributeError, IndexError, KeyError, TypeError):
                continue
        if torch_sub is None:
            raise RuntimeError("partial-stub: could not resolve `attention_pooler`")
        _instance = build(ttnn.open_device(device_id=0), torch_sub)
    return _instance(*args, **kwargs)
