# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
#
# SPDX-License-Identifier: Apache-2.0
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
"""Op-level partial TTNN port for `audio_token_detokenizer` of ACE-Step/acestep-v15-base.

Generated deterministically by `tt_hw_planner op-synth`.
Weight loading and op-REUSE/op-ADAPT helpers below are
machine-emitted from the HF reference and DO NOT need LLM
review. The `__call__` implementation falls back to HF
torch so the bring-up smoke test passes immediately;
the LLM's only remaining job is to rewrite `__call__`
to call the pre-bound `_apply_*` helpers in the right
order and fill any op-NEW gaps inline.

Pre-bound deterministic helpers (op palette):
#   self._apply_embed_tokens(x) -> ttnn.linear  (in=2048, out=2048, bias=True)
#   self._apply_layers_0_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_layers_0_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_layers_0_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_layers_0_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_layers_0_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_layers_0_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_layers_0_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_layers_0_mlp_act_fn(x) -> ttnn.silu
#   self._apply_layers_1_self_attn_q_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_layers_1_self_attn_k_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_layers_1_self_attn_v_proj(x) -> ttnn.linear  (in=2048, out=1024, bias=False)
#   self._apply_layers_1_self_attn_o_proj(x) -> ttnn.linear  (in=2048, out=2048, bias=False)
#   self._apply_layers_1_mlp_gate_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_layers_1_mlp_up_proj(x) -> ttnn.linear  (in=2048, out=6144, bias=False)
#   self._apply_layers_1_mlp_down_proj(x) -> ttnn.linear  (in=6144, out=2048, bias=False)
#   self._apply_layers_1_mlp_act_fn(x) -> ttnn.silu
#   self._apply_proj_out(x) -> ttnn.linear  (in=2048, out=64, bias=True)

LLM_GAPs (op-NEW — still need synthesis):
#   - norm  (Qwen3RMSNorm)
#   - rotary_emb  (Qwen3RotaryEmbedding)
#   - layers.0.self_attn.q_norm  (Qwen3RMSNorm)
#   - layers.0.self_attn.k_norm  (Qwen3RMSNorm)
#   - layers.0.input_layernorm  (Qwen3RMSNorm)
#   - layers.0.post_attention_layernorm  (Qwen3RMSNorm)
#   - layers.1.self_attn.q_norm  (Qwen3RMSNorm)
#   - layers.1.self_attn.k_norm  (Qwen3RMSNorm)
#   - layers.1.input_layernorm  (Qwen3RMSNorm)
#   - layers.1.post_attention_layernorm  (Qwen3RMSNorm)

HF reference: transformers/src/transformers/models/acestep/modeling_acestep.py
Op counts: total=28  op-REUSE=18  op-ADAPT=0  op-NEW=10"""

from __future__ import annotations

import torch
import transformers

import ttnn

HF_MODEL_ID = "ACE-Step/acestep-v15-base"
_CANDIDATE_SUBMODULE_PATHS = ["detokenizer"]


def _log_runtime_fallback(helper, kind, reason):
    """Append a structured CPU-fallback event for the planner reporter.

    Best-effort; never raises and never blocks the test. Writes to
    `<demo_dir>/_runtime_fallbacks.jsonl` (or the path in env
    TT_HW_PLANNER_RUNTIME_FALLBACK_LOG). The planner truncates this file
    before each pytest invocation and consumes it afterwards.
    """
    try:
        import json as _json
        import os as _os
        import sys as _sys
        import time as _time
        from pathlib import Path as _Path

        _sys.stderr.write("[%s_CPU_FALLBACK] %s: %s\n" % (kind.upper(), helper, reason))
        log_env = _os.environ.get("TT_HW_PLANNER_RUNTIME_FALLBACK_LOG")
        if log_env:
            log_path = _Path(log_env)
        else:
            # _stubs/<safe>.py  ->  demo_dir = parents[1]
            log_path = _Path(__file__).resolve().parents[1] / "_runtime_fallbacks.jsonl"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        ev = {
            "component": _Path(__file__).stem,
            "helper": helper,
            "kind": kind,
            "reason": reason,
            "ts": _time.time(),
        }
        with log_path.open("a") as f:
            f.write(_json.dumps(ev) + "\n")
    except Exception:
        pass


_LLM_GAPS = [
    {"name": "norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "rotary_emb", "class": "Qwen3RotaryEmbedding", "notes": ""},
    {"name": "layers.0.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.0.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.0.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.0.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.1.self_attn.q_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.1.self_attn.k_norm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.1.input_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
    {"name": "layers.1.post_attention_layernorm", "class": "Qwen3RMSNorm", "notes": ""},
]


def _resolve(obj, dotted):
    cur = obj
    for tok in dotted.replace("[", ".").replace("]", "").split("."):
        if tok == "":
            continue
        if tok.isdigit():
            cur = cur[int(tok)]
        else:
            cur = getattr(cur, tok)
    return cur


def _coerce_to_torch(x):
    try:
        import ttnn as _ttnn

        if isinstance(x, _ttnn.Tensor):
            import torch as _torch

            t = _ttnn.to_torch(x)
            # Bug Y fix (2026-05-23 live-run sam2-hiera-tiny)
            if t.is_floating_point():
                if t.dtype != _torch.float32:
                    t = t.to(_torch.float32)
            elif t.dtype != _torch.bool:
                t = t.to(_torch.long)
            return t
    except Exception:
        pass
    if isinstance(x, tuple):
        return tuple(_coerce_to_torch(e) for e in x)
    if isinstance(x, list):
        return [_coerce_to_torch(e) for e in x]
    if isinstance(x, dict):
        return {k: _coerce_to_torch(v) for k, v in x.items()}
    return x


class AudioTokenDetokenizer:
    def __init__(self, device, torch_module):
        self.device = device
        self._torch_module = torch_module
        sd = torch_module.state_dict()
        # op-REUSE: embed_tokens  (Linear 2048 -> 2048, bias=True)
        self.w_embed_tokens_weight = ttnn.from_torch(
            sd["embed_tokens.weight"].T.contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )
        self.w_embed_tokens_bias = ttnn.from_torch(
            sd["embed_tokens.bias"].reshape(1, -1), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # op-REUSE: layers.0.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_layers_0_self_attn_q_proj_weight = ttnn.from_torch(
            sd["layers.0.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_layers_0_self_attn_k_proj_weight = ttnn.from_torch(
            sd["layers.0.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_layers_0_self_attn_v_proj_weight = ttnn.from_torch(
            sd["layers.0.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_layers_0_self_attn_o_proj_weight = ttnn.from_torch(
            sd["layers.0.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_layers_0_mlp_gate_proj_weight = ttnn.from_torch(
            sd["layers.0.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_layers_0_mlp_up_proj_weight = ttnn.from_torch(
            sd["layers.0.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_layers_0_mlp_down_proj_weight = ttnn.from_torch(
            sd["layers.0.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.0.mlp.act_fn  (SILU)

        # op-REUSE: layers.1.self_attn.q_proj  (Linear 2048 -> 2048, bias=False)
        self.w_layers_1_self_attn_q_proj_weight = ttnn.from_torch(
            sd["layers.1.self_attn.q_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.self_attn.k_proj  (Linear 2048 -> 1024, bias=False)
        self.w_layers_1_self_attn_k_proj_weight = ttnn.from_torch(
            sd["layers.1.self_attn.k_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.self_attn.v_proj  (Linear 2048 -> 1024, bias=False)
        self.w_layers_1_self_attn_v_proj_weight = ttnn.from_torch(
            sd["layers.1.self_attn.v_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.self_attn.o_proj  (Linear 2048 -> 2048, bias=False)
        self.w_layers_1_self_attn_o_proj_weight = ttnn.from_torch(
            sd["layers.1.self_attn.o_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.mlp.gate_proj  (Linear 2048 -> 6144, bias=False)
        self.w_layers_1_mlp_gate_proj_weight = ttnn.from_torch(
            sd["layers.1.mlp.gate_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.mlp.up_proj  (Linear 2048 -> 6144, bias=False)
        self.w_layers_1_mlp_up_proj_weight = ttnn.from_torch(
            sd["layers.1.mlp.up_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.mlp.down_proj  (Linear 6144 -> 2048, bias=False)
        self.w_layers_1_mlp_down_proj_weight = ttnn.from_torch(
            sd["layers.1.mlp.down_proj.weight"].T.contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-REUSE: layers.1.mlp.act_fn  (SILU)

        # op-REUSE: proj_out  (Linear 2048 -> 64, bias=True)
        self.w_proj_out_weight = ttnn.from_torch(
            sd["proj_out.weight"].T.contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )
        self.w_proj_out_bias = ttnn.from_torch(
            sd["proj_out.bias"].reshape(1, -1), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # op-NEW: RMSNorm weights (final `norm`, and per-layer input/post-attention
        # layernorms + per-head q_norm/k_norm) -- not part of the deterministic
        # op-REUSE palette, but required to compute a correct forward pass.
        self.w_norm_weight = ttnn.from_torch(
            sd["norm.weight"].contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )
        self.w_layers_0_input_layernorm_weight = ttnn.from_torch(
            sd["layers.0.input_layernorm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_0_post_attention_layernorm_weight = ttnn.from_torch(
            sd["layers.0.post_attention_layernorm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_0_self_attn_q_norm_weight = ttnn.from_torch(
            sd["layers.0.self_attn.q_norm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_0_self_attn_k_norm_weight = ttnn.from_torch(
            sd["layers.0.self_attn.k_norm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_1_input_layernorm_weight = ttnn.from_torch(
            sd["layers.1.input_layernorm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_1_post_attention_layernorm_weight = ttnn.from_torch(
            sd["layers.1.post_attention_layernorm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_1_self_attn_q_norm_weight = ttnn.from_torch(
            sd["layers.1.self_attn.q_norm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )
        self.w_layers_1_self_attn_k_norm_weight = ttnn.from_torch(
            sd["layers.1.self_attn.k_norm.weight"].contiguous(),
            dtype=ttnn.bfloat16,
            layout=ttnn.TILE_LAYOUT,
            device=device,
        )

        # op-NEW: `special_tokens` learnable parameter (N x pool_window_size x hidden),
        # added to every expanded patch before the encoder-layer stack.
        self.w_special_tokens = ttnn.from_torch(
            sd["special_tokens"].contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # Shape / attention config (mirrors AceStepAttention / Qwen3-style GQA attention).
        cfg = torch_module.config
        self._eps = cfg.rms_norm_eps
        self._num_heads = cfg.num_attention_heads
        self._num_kv_heads = cfg.num_key_value_heads
        self._head_dim = getattr(cfg, "head_dim", cfg.hidden_size // cfg.num_attention_heads)
        self._n_rep = self._num_heads // self._num_kv_heads
        self._scaling = self._head_dim**-0.5
        self._pool_window_size = cfg.pool_window_size

        # op-NEW: `rotary_emb` (Qwen3RotaryEmbedding) only depends on position index
        # and config (not on runtime data). Positions inside this module always run
        # 0..pool_window_size-1 (the patch axis), so precompute cos/sin once here as
        # constant device tensors shaped (1, 1, pool_window_size, head_dim) -- ready
        # to be repeated across batch/heads inside `__call__`.
        rope_theta = getattr(cfg, "rope_theta", 10000.0)
        inv_freq = 1.0 / (rope_theta ** (torch.arange(0, self._head_dim, 2, dtype=torch.float32) / self._head_dim))
        positions = torch.arange(self._pool_window_size, dtype=torch.float32)
        freqs = torch.outer(positions, inv_freq)
        emb = torch.cat([freqs, freqs], dim=-1)
        cos = emb.cos().to(torch.bfloat16).reshape(1, 1, self._pool_window_size, self._head_dim)
        sin = emb.sin().to(torch.bfloat16).reshape(1, 1, self._pool_window_size, self._head_dim)
        self.w_rope_cos = ttnn.from_torch(cos, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)
        self.w_rope_sin = ttnn.from_torch(sin, dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device)

    def _apply_embed_tokens(self, x):
        return ttnn.linear(x, self.w_embed_tokens_weight, bias=self.w_embed_tokens_bias)

    def _apply_layers_0_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_self_attn_q_proj_weight)

    def _apply_layers_0_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_self_attn_k_proj_weight)

    def _apply_layers_0_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_self_attn_v_proj_weight)

    def _apply_layers_0_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_self_attn_o_proj_weight)

    def _apply_layers_0_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_mlp_gate_proj_weight)

    def _apply_layers_0_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_mlp_up_proj_weight)

    def _apply_layers_0_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_layers_0_mlp_down_proj_weight)

    def _apply_layers_0_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_layers_1_self_attn_q_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_self_attn_q_proj_weight)

    def _apply_layers_1_self_attn_k_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_self_attn_k_proj_weight)

    def _apply_layers_1_self_attn_v_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_self_attn_v_proj_weight)

    def _apply_layers_1_self_attn_o_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_self_attn_o_proj_weight)

    def _apply_layers_1_mlp_gate_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_mlp_gate_proj_weight)

    def _apply_layers_1_mlp_up_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_mlp_up_proj_weight)

    def _apply_layers_1_mlp_down_proj(self, x):
        return ttnn.linear(x, self.w_layers_1_mlp_down_proj_weight)

    def _apply_layers_1_mlp_act_fn(self, x):
        return ttnn.silu(x)

    def _apply_proj_out(self, x):
        return ttnn.linear(x, self.w_proj_out_weight, bias=self.w_proj_out_bias)

    # --- op-NEW helpers (Qwen3RMSNorm instances) ---

    def _apply_norm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_norm_weight)

    def _apply_layers_0_input_layernorm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_0_input_layernorm_weight)

    def _apply_layers_0_post_attention_layernorm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_0_post_attention_layernorm_weight)

    def _apply_layers_0_self_attn_q_norm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_0_self_attn_q_norm_weight)

    def _apply_layers_0_self_attn_k_norm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_0_self_attn_k_norm_weight)

    def _apply_layers_1_input_layernorm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_1_input_layernorm_weight)

    def _apply_layers_1_post_attention_layernorm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_1_post_attention_layernorm_weight)

    def _apply_layers_1_self_attn_q_norm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_1_self_attn_q_norm_weight)

    def _apply_layers_1_self_attn_k_norm(self, x):
        return ttnn.rms_norm(x, epsilon=self._eps, weight=self.w_layers_1_self_attn_k_norm_weight)

    def _apply_rotate_half(self, x):
        # rotate_half(x) = cat(-x2, x1) where x1, x2 are the two halves of the last dim.
        head_dim = x.shape[-1]
        half = head_dim // 2
        x1 = x[..., :half]
        x2 = x[..., half:]
        return ttnn.concat([ttnn.neg(x2), x1], dim=-1)

    def _apply_rope(self, x, cos, sin):
        return ttnn.add(ttnn.mul(x, cos), ttnn.mul(self._apply_rotate_half(x), sin))

    def _apply_encoder_layer(self, hidden_states, layer_idx, cos, sin):
        # Mirrors `AceStepEncoderLayer.forward` (pre-norm self-attn + pre-norm MLP,
        # both with residual connections). `cos`/`sin` are pre-broadcast to
        # (bsz, 1, seq_len, head_dim).
        bsz = hidden_states.shape[0]
        seq_len = hidden_states.shape[1]
        prefix = "layers_%d_" % layer_idx

        q_proj = getattr(self, "_apply_%sself_attn_q_proj" % prefix)
        k_proj = getattr(self, "_apply_%sself_attn_k_proj" % prefix)
        v_proj = getattr(self, "_apply_%sself_attn_v_proj" % prefix)
        o_proj = getattr(self, "_apply_%sself_attn_o_proj" % prefix)
        gate_proj = getattr(self, "_apply_%smlp_gate_proj" % prefix)
        up_proj = getattr(self, "_apply_%smlp_up_proj" % prefix)
        down_proj = getattr(self, "_apply_%smlp_down_proj" % prefix)
        act_fn = getattr(self, "_apply_%smlp_act_fn" % prefix)
        input_ln = getattr(self, "_apply_%sinput_layernorm" % prefix)
        post_ln = getattr(self, "_apply_%spost_attention_layernorm" % prefix)
        q_norm = getattr(self, "_apply_%sself_attn_q_norm" % prefix)
        k_norm = getattr(self, "_apply_%sself_attn_k_norm" % prefix)

        # --- Self-attention block ---
        residual = hidden_states
        normed = input_ln(hidden_states)

        q = q_proj(normed)
        q = ttnn.reshape(q, (bsz, seq_len, self._num_heads, self._head_dim))
        q = q_norm(q)
        q = ttnn.transpose(q, 1, 2)  # (B, num_heads, L, head_dim)

        k = k_proj(normed)
        k = ttnn.reshape(k, (bsz, seq_len, self._num_kv_heads, self._head_dim))
        k = k_norm(k)
        k = ttnn.transpose(k, 1, 2)  # (B, num_kv_heads, L, head_dim)

        v = v_proj(normed)
        v = ttnn.reshape(v, (bsz, seq_len, self._num_kv_heads, self._head_dim))
        v = ttnn.transpose(v, 1, 2)  # (B, num_kv_heads, L, head_dim)

        # `cos`/`sin` are (1, 1, P, head_dim); ttnn elementwise ops broadcast
        # singleton batch/head dims automatically against q/k's
        # (bsz, num_heads_or_kv, P, head_dim), so no explicit repeat is needed.
        q = self._apply_rope(q, cos, sin)
        k = self._apply_rope(k, cos, sin)

        # GQA: expand key/value heads to match query heads (repeat_kv == repeat_interleave).
        if self._n_rep > 1:
            k = ttnn.repeat_interleave(k, self._n_rep, dim=1)
            v = ttnn.repeat_interleave(v, self._n_rep, dim=1)

        # No attention mask needed: these encoder layers are bidirectional
        # (is_causal=False) and this module never receives padding; the
        # sliding-window layer's window (128) is >> the patch sequence
        # length (pool_window_size), so it is equivalent to full attention
        # for this component's fixed, tiny sequence length.
        attn_weights = ttnn.matmul(q, ttnn.transpose(k, 2, 3))  # (B, num_heads, L, L)
        attn_weights = ttnn.mul(attn_weights, self._scaling)
        attn_weights = ttnn.softmax(attn_weights, dim=-1)

        attn_output = ttnn.matmul(attn_weights, v)  # (B, num_heads, L, head_dim)
        attn_output = ttnn.transpose(attn_output, 1, 2)  # (B, L, num_heads, head_dim)
        attn_output = ttnn.reshape(attn_output, (bsz, seq_len, self._num_heads * self._head_dim))
        attn_output = o_proj(attn_output)

        hidden_states = ttnn.add(residual, attn_output)

        # --- MLP block ---
        residual = hidden_states
        normed = post_ln(hidden_states)
        gate = act_fn(gate_proj(normed))
        up = up_proj(normed)
        mlp_out = down_proj(ttnn.mul(gate, up))
        hidden_states = ttnn.add(residual, mlp_out)

        return hidden_states

    def __call__(self, x, attention_mask=None, **kwargs):
        # x: (B, T, hidden_size) quantized-audio-token embeddings.
        B = x.shape[0]
        T = x.shape[1]
        D = x.shape[2]
        P = self._pool_window_size

        # Project tokens into hidden space.
        embedded = self._apply_embed_tokens(x)  # (B, T, D)

        # Expand each token into `pool_window_size` patches: (B, T, D) -> (B*T, P, D).
        embedded = ttnn.reshape(embedded, (B * T, 1, D))
        embedded = ttnn.repeat(embedded, ttnn.Shape([1, P, 1]))  # (B*T, P, D)

        # Add the learnable per-patch special tokens (broadcast across B*T).
        special = ttnn.repeat(self.w_special_tokens, ttnn.Shape([B * T, 1, 1]))  # (B*T, P, D)
        hidden_states = ttnn.add(embedded, special)

        # RoPE cos/sin for positions 0..P-1: (1, 1, P, head_dim). Broadcasts
        # directly against q/k of shape (B*T, num_heads_or_kv, P, head_dim)
        # inside `_apply_encoder_layer` -- no repeat needed.
        cos = self.w_rope_cos
        sin = self.w_rope_sin

        hidden_states = self._apply_encoder_layer(hidden_states, 0, cos, sin)
        hidden_states = self._apply_encoder_layer(hidden_states, 1, cos, sin)

        hidden_states = self._apply_norm(hidden_states)
        hidden_states = self._apply_proj_out(hidden_states)  # (B*T, P, audio_acoustic_hidden_dim)

        out_dim = hidden_states.shape[-1]
        hidden_states = ttnn.reshape(hidden_states, (B, T * P, out_dim))
        return hidden_states


def build(device, torch_module):
    return AudioTokenDetokenizer(device, torch_module)


_instance = None


def audio_token_detokenizer(*args, **kwargs):
    global _instance
    if _instance is None:
        model = transformers.AutoModel.from_pretrained(
            HF_MODEL_ID, trust_remote_code=True, torch_dtype="bfloat16", low_cpu_mem_usage=True
        )
        model.eval()
        torch_sub = None
        for path in _CANDIDATE_SUBMODULE_PATHS:
            try:
                torch_sub = _resolve(model, path)
                break
            except (AttributeError, IndexError, KeyError, TypeError):
                continue
        if torch_sub is None:
            raise RuntimeError("partial-stub: could not resolve `audio_token_detokenizer`")
        _instance = build(ttnn.open_device(device_id=0), torch_sub)
    return _instance(*args, **kwargs)
