# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
#
# SPDX-License-Identifier: Apache-2.0
# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
"""Op-level partial TTNN port for `residual_f_s_q` of ACE-Step/acestep-v15-base.

Generated deterministically by `tt_hw_planner op-synth`.
Weight loading and op-REUSE/op-ADAPT helpers below are
machine-emitted from the HF reference and DO NOT need LLM
review. The `__call__` implementation falls back to HF
torch so the bring-up smoke test passes immediately;
the LLM's only remaining job is to rewrite `__call__`
to call the pre-bound `_apply_*` helpers in the right
order and fill any op-NEW gaps inline.

Pre-bound deterministic helpers (op palette):
#   self._apply_project_in(x) -> ttnn.linear  (in=2048, out=6, bias=True)
#   self._apply_project_out(x) -> ttnn.linear  (in=6, out=2048, bias=True)

LLM_GAPs (op-NEW — still need synthesis):
#   - layers.0.project_in  (Identity)
#   - layers.0.project_out  (Identity)

HF reference: transformers/src/transformers/models/acestep/modeling_acestep.py
Op counts: total=4  op-REUSE=4  op-ADAPT=0  op-NEW=0"""

from __future__ import annotations

import torch
import transformers

import ttnn
from models.demos.hf_eager.acestep_v15_base._stubs.f_s_q import build as _fsq_build

HF_MODEL_ID = "ACE-Step/acestep-v15-base"
_CANDIDATE_SUBMODULE_PATHS = ["tokenizer.quantizer"]


def _log_runtime_fallback(helper, kind, reason):
    """Append a structured CPU-fallback event for the planner reporter.

    Best-effort; never raises and never blocks the test. Writes to
    `<demo_dir>/_runtime_fallbacks.jsonl` (or the path in env
    TT_HW_PLANNER_RUNTIME_FALLBACK_LOG). The planner truncates this file
    before each pytest invocation and consumes it afterwards.
    """
    try:
        import json as _json
        import os as _os
        import sys as _sys
        import time as _time
        from pathlib import Path as _Path

        _sys.stderr.write("[%s_CPU_FALLBACK] %s: %s\n" % (kind.upper(), helper, reason))
        log_env = _os.environ.get("TT_HW_PLANNER_RUNTIME_FALLBACK_LOG")
        if log_env:
            log_path = _Path(log_env)
        else:
            # _stubs/<safe>.py  ->  demo_dir = parents[1]
            log_path = _Path(__file__).resolve().parents[1] / "_runtime_fallbacks.jsonl"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        ev = {
            "component": _Path(__file__).stem,
            "helper": helper,
            "kind": kind,
            "reason": reason,
            "ts": _time.time(),
        }
        with log_path.open("a") as f:
            f.write(_json.dumps(ev) + "\n")
    except Exception:
        pass


_LLM_GAPS = [
    {"name": "layers.0.project_in", "class": "Identity", "notes": ""},
    {"name": "layers.0.project_out", "class": "Identity", "notes": ""},
]


def _resolve(obj, dotted):
    cur = obj
    for tok in dotted.replace("[", ".").replace("]", "").split("."):
        if tok == "":
            continue
        if tok.isdigit():
            cur = cur[int(tok)]
        else:
            cur = getattr(cur, tok)
    return cur


def _coerce_to_torch(x):
    try:
        import ttnn as _ttnn

        if isinstance(x, _ttnn.Tensor):
            import torch as _torch

            t = _ttnn.to_torch(x)
            # Bug Y fix (2026-05-23 live-run sam2-hiera-tiny)
            if t.is_floating_point():
                if t.dtype != _torch.float32:
                    t = t.to(_torch.float32)
            elif t.dtype != _torch.bool:
                t = t.to(_torch.long)
            return t
    except Exception:
        pass
    if isinstance(x, tuple):
        return tuple(_coerce_to_torch(e) for e in x)
    if isinstance(x, list):
        return [_coerce_to_torch(e) for e in x]
    if isinstance(x, dict):
        return {k: _coerce_to_torch(v) for k, v in x.items()}
    return x


class ResidualFSQ:
    def __init__(self, device, torch_module):
        self.device = device
        self._torch_module = torch_module
        sd = torch_module.state_dict()
        # op-REUSE: project_in  (Linear 2048 -> 6, bias=True)
        self.w_project_in_weight = ttnn.from_torch(
            sd["project_in.weight"].T.contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )
        self.w_project_in_bias = ttnn.from_torch(
            sd["project_in.bias"].reshape(1, -1), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # op-REUSE: project_out  (Linear 6 -> 2048, bias=True)
        self.w_project_out_weight = ttnn.from_torch(
            sd["project_out.weight"].T.contiguous(), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )
        self.w_project_out_bias = ttnn.from_torch(
            sd["project_out.bias"].reshape(1, -1), dtype=ttnn.bfloat16, layout=ttnn.TILE_LAYOUT, device=device
        )

        # Delegate the single per-layer FSQ quantization (num_quantizers == 1)
        # to the f_s_q leaf stub built on quantizer.layers[0].
        self._fsq_stub = _fsq_build(device, torch_module.layers[0])

        # ResidualFSQ soft (tanh) clamp on the project_in output, applied before
        # the per-layer FSQ hard clamp/quantize: x = tanh(x / cv) * cv, with
        # cv = 1 + 1/(levels-1) per codebook dim. Read off the module's own
        # non-persistent buffer for exactness.
        _cv = torch_module.soft_clamp_input_value.detach().to(torch.float32).reshape(1, 1, -1)
        self.w_clamp_value = ttnn.from_torch(_cv, dtype=ttnn.float32, layout=ttnn.TILE_LAYOUT, device=device)
        self.w_inv_clamp_value = ttnn.from_torch(1.0 / _cv, dtype=ttnn.float32, layout=ttnn.TILE_LAYOUT, device=device)

    def _mm_cfg(self):
        return ttnn.WormholeComputeKernelConfig(
            math_fidelity=ttnn.MathFidelity.HiFi4,
            math_approx_mode=False,
            fp32_dest_acc_en=True,
            packer_l1_acc=True,
        )

    def _lin_f32(self, x, weight, bias, compute_kernel_config):
        return ttnn.linear(
            x,
            ttnn.typecast(weight, ttnn.float32),
            bias=ttnn.typecast(bias, ttnn.float32),
            compute_kernel_config=compute_kernel_config,
        )

    def _apply_project_in(self, x):
        return ttnn.linear(x, self.w_project_in_weight, bias=self.w_project_in_bias)

    def _apply_project_out(self, x):
        return ttnn.linear(x, self.w_project_out_weight, bias=self.w_project_out_bias)

    def __call__(self, *args, **kwargs):
        x = args[0] if args else kwargs.get("z", None)

        # Run project_in / soft-clamp / project_out in float32 with HiFi4 dest
        # accumulation: the FSQ floor() at the tail is a step function, so the
        # pre-quantization activation must track the fp32 reference to well
        # within a bin width or codes flip and project_out smears the error.
        mm = self._mm_cfg()
        x = ttnn.typecast(x, ttnn.float32)

        # project_in: 2048 -> 6
        z = self._lin_f32(x, self.w_project_in_weight, self.w_project_in_bias, mm)

        # ResidualFSQ tanh soft-clamp before the per-layer FSQ layer.
        z = ttnn.mul(z, self.w_inv_clamp_value)
        z = ttnn.tanh(z)
        z = ttnn.mul(z, self.w_clamp_value)

        # Per-layer FSQ quantization via the f_s_q leaf stub (num_quantizers==1,
        # scale==levels**0==1, so residual bookkeeping collapses to identity).
        # The f_s_q stub consumes the projected codes [1, 10, 6] as a ttnn tensor
        # (it upcasts to fp32 internally) and returns (codes[1,10,6], idx[1,10]).
        codes, idx = self._fsq_stub(z)

        # indices -> (B, N, 1) to honour the ResidualFSQ return contract.
        idx = ttnn.unsqueeze(idx, dim=-1)

        # project_out: 6 -> 2048
        reconstructed = self._lin_f32(codes, self.w_project_out_weight, self.w_project_out_bias, mm)

        return (reconstructed, idx)


def build(device, torch_module):
    return ResidualFSQ(device, torch_module)


_instance = None


def residual_f_s_q(*args, **kwargs):
    global _instance
    if _instance is None:
        model = transformers.AutoModel.from_pretrained(
            HF_MODEL_ID, trust_remote_code=True, torch_dtype="bfloat16", low_cpu_mem_usage=True
        )
        model.eval()
        torch_sub = None
        for path in _CANDIDATE_SUBMODULE_PATHS:
            try:
                torch_sub = _resolve(model, path)
                break
            except (AttributeError, IndexError, KeyError, TypeError):
                continue
        if torch_sub is None:
            raise RuntimeError("partial-stub: could not resolve `residual_f_s_q`")
        _instance = build(ttnn.open_device(device_id=0), torch_sub)
    return _instance(*args, **kwargs)
