# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
# SPDX-License-Identifier: Apache-2.0
# >>> MACHINE-GENERATED stub (ADAPT — canonical-wrapper path) <<<
"""Pure-TTNN Mamba2 SSD mixer for `nemotron_h_mamba2_mixer`.

The canonical `TtMambaSSM` (models/demos/wormhole/mamba/tt/mamba_ssm.py) is a
Mamba1 SSM kernel keyed on `mixer.x_proj.weight` / `mixer.dt_proj.weight` —
keys that DO NOT EXIST in a NemotronH Mamba2 mixer (which fuses everything in
`in_proj` and carries `A_log`/`D`/`dt_bias`/`conv1d`/`norm`). It is structurally
inapplicable to Mamba2 SSD, so this stub computes the forward with native
`ttnn.*` ops. The canonical import is retained per the ADAPT requirement.

The captured I/O contract is a SINGLE chunk (seq <= chunk_size=128), so the
chunked SSD reduces to the quadratic ("attention") form within one chunk:

    a_t        = A_h * dt_t                       (per head, scalar decay)
    A_cum_t    = sum_{k<=t} a_k                    (causal cumulative sum)
    L[t,s]     = exp(A_cum_t - A_cum_s)            for s<=t, else 0
    CB[t,s]    = sum_n C_t[n] * B_s[n]             (group-shared)
    M[t,s]     = CB[t,s] * L[t,s]
    Y[t,d]     = sum_s M[t,s] * (dt_s * x_s[d]) + D_h * x_t[d]

Then gated grouped-RMSNorm and out_proj. Everything stays on device.
"""
from __future__ import annotations

import torch

import ttnn
from models.demos.nvidia_nemotron_3_5_lightning_30b_a3b_bf16._stubs import _dram_mm, _ssm_cache
from models.demos.wormhole.mamba.tt.mamba_ssm import TtMambaSSM  # kept per ADAPT requirement


class TtNemotronHMamba2Mixer:
    def __init__(self, device, torch_module) -> None:
        self.device = device

        self.num_heads = int(torch_module.num_heads)  # 64
        self.head_dim = int(torch_module.head_dim)  # 64
        self.intermediate_size = int(torch_module.intermediate_size)  # 4096
        self.ssm_state_size = int(torch_module.ssm_state_size)  # 128
        self.n_groups = int(torch_module.n_groups)  # 8
        self.chunk_size = int(torch_module.chunk_size)  # 128
        self.hidden_size = int(torch_module.hidden_size)  # 2688
        self.conv_dim = int(torch_module.conv_dim)  # 6144
        self.time_step_limit = tuple(torch_module.time_step_limit)
        # norm config
        norm = torch_module.norm
        self.norm_eps = float(getattr(norm, "variance_epsilon", getattr(torch_module, "layer_norm_epsilon", 1e-5)))
        self.norm_group_size = int(getattr(norm, "group_size", self.intermediate_size // self.n_groups))  # 512

        sd = torch_module.state_dict()
        H = self.num_heads

        # FULL (unsharded) Mamba2 dims used to build the weight reordering.
        Hf, HD, Nn = self.num_heads, self.head_dim, self.ssm_state_size  # 64,64,128
        Gf = self.n_groups  # 8
        INTERf = self.intermediate_size  # 4096
        GGNf = Gf * Nn  # 1024
        reps = Hf // Gf  # 8

        # ---- tensor-parallel (head-parallel) config -----------------------
        # ONLY shard under the shard runner; the single-device .last_good_native
        # path stays byte-identical (TP=1 => replicated, exactly as before).
        # Mamba TP = split the HEADS across chips: the SSD scan is per-head
        # independent, so each chip runs Hl=H/TP heads (and the matching
        # Gl=G/TP conv groups, reps preserved) end-to-end with NO cross-head
        # comms. in_proj is column-parallel (replicated x, sharded proj); out_proj
        # is row-parallel (sharded in -> partial sums -> one all_reduce). On this
        # box fabric only trains on the full mesh, so the run lands on a 2-D
        # MeshShape(DP,TP): shard the TP (last) axis, replicate the DP axis.
        import os as _os

        dev = self.device
        try:
            _is_mesh = isinstance(dev, ttnn.MeshDevice)
        except AttributeError:
            _is_mesh = False
        _mesh_shape = list(dev.shape) if _is_mesh else [1, 1]
        shard = bool(_os.environ.get("TT_HW_PLANNER_SHARD_RUN")) and _is_mesh
        TP = _mesh_shape[-1] if shard else 1
        shard = shard and TP > 1 and (Hf % TP == 0) and (Gf % TP == 0)
        self._shard = shard
        self._TP = TP
        self._tp_axis = len(_mesh_shape) - 1
        self._mesh_shape = _mesh_shape
        Hl, Gl = Hf // TP, Gf // TP
        INTERl, GGNl = Hl * HD, Gl * Nn

        # ---- depthwise causal conv1d weights, decomposed per tap ----
        w_conv = sd["conv1d.weight"].squeeze(1).float()  # (6144, K)
        self.conv_k = int(w_conv.shape[1])
        K = self.conv_k
        cb = sd.get("conv1d.bias")

        if shard:
            # Column permutation of in_proj's 10304 outputs so each chip's heads'
            # [gate | x | B | C | dt] land in one contiguous block that dim-1
            # sharding then splits evenly. Layout of proj:
            #   gate[0:INTER] x[INTER:2INTER] B[2INTER:2INTER+GGN]
            #   C[2INTER+GGN:2INTER+2GGN] dt[2INTER+2GGN:]
            incol, cvcol = [], []
            for d in range(TP):
                hs, he = d * Hl, (d + 1) * Hl
                gs, ge = d * Gl, (d + 1) * Gl
                incol += list(range(hs * HD, he * HD))  # gate
                incol += list(range(INTERf + hs * HD, INTERf + he * HD))  # x
                incol += list(range(2 * INTERf + gs * Nn, 2 * INTERf + ge * Nn))  # B
                incol += list(range(2 * INTERf + GGNf + gs * Nn, 2 * INTERf + GGNf + ge * Nn))  # C
                incol += list(range(2 * INTERf + 2 * GGNf + hs, 2 * INTERf + 2 * GGNf + he))  # dt
                # conv operates on conv_dim = [x(INTER) | B(GGN) | C(GGN)] channels.
                cvcol += list(range(hs * HD, he * HD))  # x
                cvcol += list(range(INTERf + gs * Nn, INTERf + ge * Nn))  # B
                cvcol += list(range(INTERf + GGNf + gs * Nn, INTERf + GGNf + ge * Nn))  # C
            incol = torch.tensor(incol, dtype=torch.long)
            cvcol = torch.tensor(cvcol, dtype=torch.long)

            Win = sd["in_proj.weight"].t().contiguous().float()[:, incol]  # (2688, 10304)
            self._w_in = self._shd_bf16(Win, 1, dtype=ttnn.bfloat8_b)  # col-parallel
            # out_proj row-parallel: heads are contiguous in d_inner, so a plain
            # dim-0 split lines each chip's input rows up with its heads' y.
            self._w_out = self._shd_bf16(sd["out_proj.weight"].t().contiguous().float(), 0, dtype=ttnn.bfloat8_b)

            w_conv_r = w_conv[cvcol]  # (conv_dim, K) reordered
            self._conv_taps = [self._shd(w_conv_r[:, K - 1 - s].reshape(1, 1, -1), 2) for s in range(K)]
            self._conv_bias = self._shd(cb.float()[cvcol].reshape(1, 1, -1), 2) if cb is not None else None

            A = -torch.exp(sd["A_log"].float())  # (H,)
            self._A = self._shd(A.reshape(1, Hf, 1, 1), 1)
            self._D = self._shd(sd["D"].float().reshape(1, Hf, 1, 1), 1)
            self._dt_bias = self._shd(sd["dt_bias"].float().reshape(1, 1, Hf), 2)
            self._norm_w_full = self._shd(sd["norm.weight"].float().reshape(1, 1, INTERf), 2)

            # local group->head matrix [Gl*N, Hl*N]; reps preserved by the head
            # split so this is identical on every chip -> replicated.
            P = torch.zeros(GGNl, Hl * Nn, dtype=torch.float32)
            for h in range(Hl):
                g = h // reps
                P[g * Nn : (g + 1) * Nn, h * Nn : (h + 1) * Nn] = torch.eye(Nn, dtype=torch.float32)
            self._P = self._dev(P)
        else:
            # ---- big projection weights (stored pre-transposed: [in, out]) ----
            self._w_in = self._devw_bf16(
                sd["in_proj.weight"].t().contiguous().float(), dtype=ttnn.bfloat8_b
            )  # (2688, 10304)
            self._w_out = self._devw_bf16(
                sd["out_proj.weight"].t().contiguous().float(), dtype=ttnn.bfloat8_b
            )  # (4096, 2688)
            # tap s shifts the sequence by s (x[t-s]); its weight column is K-1-s.
            self._conv_taps = [self._dev(w_conv[:, K - 1 - s].reshape(1, 1, self.conv_dim)) for s in range(K)]
            self._conv_bias = self._dev(cb.float().reshape(1, 1, self.conv_dim)) if cb is not None else None
            G, N = self.n_groups, self.ssm_state_size
            P = torch.zeros(G * N, H * N, dtype=torch.float32)
            for h in range(H):
                g = h // reps
                P[g * N : (g + 1) * N, h * N : (h + 1) * N] = torch.eye(N, dtype=torch.float32)
            self._P = self._dev(P)
            A = -torch.exp(sd["A_log"].float())  # (H,)
            self._A = self._dev(A.reshape(1, H, 1, 1))
            self._D = self._dev(sd["D"].float().reshape(1, H, 1, 1))
            self._dt_bias = self._dev(sd["dt_bias"].float().reshape(1, 1, H))
            self._norm_w_full = self._dev(sd["norm.weight"].float().reshape(1, 1, self.intermediate_size))

        self._norm_ones = self._dev(torch.ones(1, 1, self.norm_group_size, dtype=torch.float32))

        # Under head-parallel every per-head/per-group dim the forward reads is
        # LOCAL, so one program with local dims runs correctly on each symmetric
        # chip. norm_group_size (=512) is unchanged by the split.
        if shard:
            self.num_heads = Hl
            self.n_groups = Gl
            self.intermediate_size = INTERl
            self.conv_dim = INTERl + 2 * GGNl

        # per-seq-length constant cache (tril / decay-broadcast / shift mats)
        self._consts = {}

        self.ckc = ttnn.WormholeComputeKernelConfig(
            math_fidelity=ttnn.MathFidelity.HiFi4,
            math_approx_mode=False,
            fp32_dest_acc_en=True,
            packer_l1_acc=True,
        )

    # ------------------------------------------------------------------ #
    @classmethod
    def build(cls, device, torch_module):
        return cls(device, torch_module)

    # ----------------------------- helpers ---------------------------- #
    def _is_mesh(self):
        try:
            if isinstance(self.device, ttnn.MeshDevice):
                return True
        except AttributeError:
            pass
        return hasattr(self.device, "get_device_ids") or hasattr(self.device, "get_devices")

    def _dev(self, torch_tensor, layout=ttnn.TILE_LAYOUT):
        """Upload an fp32 torch constant to device, mesh-replicated."""
        if self._is_mesh():
            try:
                return ttnn.from_torch(
                    torch_tensor,
                    dtype=ttnn.float32,
                    layout=layout,
                    device=self.device,
                    mesh_mapper=ttnn.ReplicateTensorToMesh(self.device),
                )
            except Exception:
                pass
        return ttnn.from_torch(torch_tensor, dtype=ttnn.float32, layout=layout, device=self.device)

    def _shd(self, torch_tensor, dim, layout=ttnn.TILE_LAYOUT):
        """Upload an fp32 torch weight sharded along `dim` on the TP (last) mesh
        axis and replicated on the DP axis (2-D MeshShape(DP,TP))."""
        return ttnn.from_torch(
            torch_tensor,
            dtype=ttnn.float32,
            layout=layout,
            device=self.device,
            mesh_mapper=ttnn.ShardTensor2dMesh(self.device, mesh_shape=self._mesh_shape, dims=(None, dim)),
        )

    def _devw_bf16(self, torch_tensor, layout=ttnn.TILE_LAYOUT, dtype=ttnn.bfloat16):
        """Projection weight, bf16 unless `dtype` says otherwise (in_proj/out_proj only -- NOT the SSM scan
        constants A/D/dt_bias, which stay fp32 for the decay/softplus math)."""
        t16 = torch_tensor.to(torch.bfloat16)
        if self._is_mesh():
            try:
                return ttnn.from_torch(
                    t16,
                    dtype=dtype,
                    layout=layout,
                    device=self.device,
                    mesh_mapper=ttnn.ReplicateTensorToMesh(self.device),
                )
            except Exception:
                pass
        return ttnn.from_torch(t16, dtype=dtype, layout=layout, device=self.device)

    def _shd_bf16(self, torch_tensor, dim, layout=ttnn.TILE_LAYOUT, dtype=ttnn.bfloat16):
        """Projection weight sharded along `dim` (see _shd, _devw_bf16)."""
        return ttnn.from_torch(
            torch_tensor.to(torch.bfloat16),
            dtype=dtype,
            layout=layout,
            device=self.device,
            mesh_mapper=ttnn.ShardTensor2dMesh(self.device, mesh_shape=self._mesh_shape, dims=(None, dim)),
        )

    def _fp32(self, t):
        if isinstance(t, ttnn.Tensor):
            if t.dtype != ttnn.float32:
                return ttnn.typecast(t, ttnn.float32)
            return t
        return self._dev(t.float())

    def _softplus(self, x):
        """softplus(x) = log(1 + exp(x)); stable form relu(x) + log1p(exp(-|x|)).

        ttnn.softplus default args are unreliable on this build (see project
        memory), so use the numerically-stable manual form built from ops the
        graduated siblings confirm exist.
        """
        relu_x = ttnn.relu(x)
        abs_x = ttnn.abs(x)
        neg_abs = ttnn.multiply(abs_x, -1.0)
        ttnn.deallocate(abs_x)
        e = ttnn.exp(neg_abs)
        ttnn.deallocate(neg_abs)
        log_term = ttnn.log1p(e)
        ttnn.deallocate(e)
        out = ttnn.add(relu_x, log_term)
        ttnn.deallocate(relu_x)
        ttnn.deallocate(log_term)
        return out

    def _get_consts(self, B, T):
        # Keyed on (B, T). ttnn.matmul HANGS on a PARTIAL batch broadcast (lhs
        # batch 1 against rhs batch B), so a constant that is a matmul OPERAND
        # must either match the real batch or have ALL its batch dims equal to 1.
        # `neg` therefore stays (1,1,T,T); `tril` (the cumsum operand) and
        # `shifts` are materialised at the real batch.
        c = self._consts.get((B, T))
        if c is not None:
            return c
        tril2d = torch.tril(torch.ones(T, T, dtype=torch.float32))  # (T,T)
        # at the real (B, H) batch so the cumsum runs as a head-spread heads_matmul
        tril = tril2d.reshape(1, 1, T, T).expand(B, self.num_heads, T, T).contiguous()
        # additive causal mask (0 on/below diagonal, -1e9 above); elementwise add
        neg = ((1.0 - tril2d) * (-1e9)).reshape(1, 1, T, T).contiguous()
        # shift matrices for the depthwise causal conv: Sh_s @ x => x[t-s]
        shifts = []
        for s in range(self.conv_k):
            m = torch.zeros(T, T, dtype=torch.float32)
            for t in range(T):
                if t - s >= 0:
                    m[t, t - s] = 1.0
            shifts.append(self._dev(m.reshape(1, T, T).repeat(B, 1, 1)))
        c = {
            "tril": self._dev(tril),
            "neg": self._dev(neg),
            "shifts": shifts,
        }
        self._consts[(B, T)] = c
        return c

    def _to_heads(self, t, B, T, n, d):
        """(B, T, n*d) tile -> (B, n, T, d) tile."""
        return _ssm_cache.to_heads(t, B, T, n, d)

    def _out_proj(self, y, B, T):
        """out_proj over (1, B*T) token rows; the full-grid config at decode."""
        out = ttnn.matmul(
            _dram_mm.as_rows(y), self._w_out, compute_kernel_config=self.ckc, program_config=self._out_pc(B * T)
        )
        return _dram_mm.from_rows(out, B, T)

    def _out_pc(self, tokens):
        """Full-grid 1-D multicast config for out_proj at decode; None (ttnn's
        choice) at prefill."""
        if tokens > _dram_mm.TILE:
            return None
        return _dram_mm.mcast1d_config(self.device, int(self._w_out.shape[-2]), int(self._w_out.shape[-1]))

    def _prefill_core(self, hbc, dt, B, T, consts, fill=False):
        """Full-sequence conv + single-chunk SSD -> Y (B, H, T, HD). With
        fill=True it also writes the decode state left after position T-1."""
        H, HD, N = self.num_heads, self.head_dim, self.ssm_state_size
        I = self.intermediate_size
        G = self.n_groups
        if fill:
            self._state = getattr(self, "_state", {})
        # 3. depthwise causal conv1d via shift-matmul + per-tap channel scale
        conv_acc = ttnn.multiply(hbc, self._conv_taps[0])  # lag 0: the shift is the identity
        for s in range(1, self.conv_k):
            shifted = ttnn.matmul(consts["shifts"][s], hbc, compute_kernel_config=self.ckc)  # (B,T,conv_dim)
            conv_acc = ttnn.addcmul(conv_acc, shifted, self._conv_taps[s])  # acc + x[t-s] * tap_s in one pass
            ttnn.deallocate(shifted)
        if fill:
            hbc_pre = hbc
        else:
            ttnn.deallocate(hbc)
        if self._conv_bias is not None:
            conv_acc = ttnn.add(conv_acc, self._conv_bias)
        hbc = ttnn.silu(conv_acc)  # (B, T, conv_dim)
        ttnn.deallocate(conv_acc)

        # 4. split conv output: X(I) | B(G*N) | C(G*N)
        Xf = ttnn.slice(hbc, [0, 0, 0], [B, T, I])
        Bf = ttnn.slice(hbc, [0, 0, I], [B, T, I + G * N])
        Cf = ttnn.slice(hbc, [0, 0, I + G * N], [B, T, I + 2 * G * N])
        ttnn.deallocate(hbc)

        # 5. dt = softplus(dt + dt_bias) ; time_step_limit=(0,inf) => clamp is a no-op
        dt = ttnn.add(dt, self._dt_bias)
        dt = self._softplus(dt)
        lo, hi = self.time_step_limit
        if lo != 0.0 or hi != float("inf"):
            try:
                dt = ttnn.clamp(dt, lo, hi)
            except Exception:
                try:
                    dt = ttnn.clip(dt, lo, hi)
                except Exception:
                    pass

        # 6. B/C groups -> heads: to_heads on the G groups, then repeat each
        #    group's rows (no selection matmul, and an 8x narrower layout trip)
        X = self._to_heads(Xf, B, T, H, HD)  # (B, H, T, HD)
        ttnn.deallocate(Xf)
        Bh = ttnn.repeat_interleave(self._to_heads(Bf, B, T, G, N), H // G, dim=1)  # (B, H, T, N)
        Ch = ttnn.repeat_interleave(self._to_heads(Cf, B, T, G, N), H // G, dim=1)  # (B, H, T, N)
        ttnn.deallocate(Bf)
        ttnn.deallocate(Cf)
        dt_h = self._to_heads(dt, B, T, H, 1)  # (B, H, T, 1)
        ttnn.deallocate(dt)

        # 7. discretized X and D residual
        X_disc = ttnn.multiply(X, dt_h)  # (B, H, T, HD)
        D_res = ttnn.multiply(X, self._D)  # (B, H, T, HD)
        ttnn.deallocate(X)

        # 8. decay matrix L = exp(causal-segsum(A_h * dt))
        a = ttnn.multiply(dt_h, self._A)  # (B, H, T, 1)
        ttnn.deallocate(dt_h)
        A_cum = _ssm_cache.heads_matmul(consts["tril"], a, self.ckc)  # (B, H, T, 1) inclusive cumsum
        ttnn.deallocate(a)
        if fill:
            _ssm_cache.mamba_fill(self._state, self.device, hbc_pre, A_cum, Bh, X_disc, self.conv_k, self.ckc)
            ttnn.deallocate(hbc_pre)
        A_cum_s = ttnn.transpose(A_cum, -2, -1)  # (B,H,1,T)
        Dmat = ttnn.subtract(A_cum, A_cum_s)  # col - row broadcast: [.,t,s] = cum[t]-cum[s], no outer-product matmul
        ttnn.deallocate(A_cum)
        ttnn.deallocate(A_cum_s)
        Dmat = ttnn.add(Dmat, consts["neg"])  # mask s>t to -inf
        L = ttnn.exp(Dmat)  # (B, H, T, T)
        ttnn.deallocate(Dmat)

        # 9. CB[h] = C[h] @ B[h]^T  (per head)
        BhT = ttnn.transpose(Bh, -2, -1)  # (B, H, N, T)
        Ch16 = ttnn.typecast(Ch, ttnn.bfloat16)
        BhT16 = ttnn.typecast(BhT, ttnn.bfloat16)
        CB_h = _ssm_cache.heads_matmul(Ch16, BhT16, self.ckc)  # (B, H, T, T)
        ttnn.deallocate(Ch16)
        ttnn.deallocate(BhT16)
        ttnn.deallocate(BhT)
        ttnn.deallocate(Bh)
        ttnn.deallocate(Ch)

        # 10. M = CB * L ; Y = M @ X_disc + D_res
        M = ttnn.multiply(CB_h, L)
        ttnn.deallocate(CB_h)
        ttnn.deallocate(L)
        Y = _ssm_cache.heads_matmul(M, X_disc, self.ckc)  # (B, H, T, HD)
        ttnn.deallocate(M)
        ttnn.deallocate(X_disc)
        Y = ttnn.add(Y, D_res)
        ttnn.deallocate(D_res)

        return Y

    def _decode_core(self, hbc, dt, B):
        """Single-token conv + SSD recurrence against the cached state.
        hbc/dt are (1, B, .) token rows -> Y (B, H, 1, HD)."""
        H, HD, N = self.num_heads, self.head_dim, self.ssm_state_size
        I = self.intermediate_size
        G = self.n_groups
        hbc = _ssm_cache.mamba_conv_step(self._state, hbc, self._conv_taps, self._conv_bias, self.conv_k)
        Xf = ttnn.slice(hbc, [0, 0, 0], [1, B, I])
        Bf = ttnn.slice(hbc, [0, 0, I], [1, B, I + G * N])
        Cf = ttnn.slice(hbc, [0, 0, I + G * N], [1, B, I + 2 * G * N])
        ttnn.deallocate(hbc)
        dt = _ssm_cache.softplus(ttnn.add(dt, self._dt_bias))
        X = self._to_heads(Xf, B, 1, H, HD)
        # group -> head expansion as a repeat of each group's row (no P-matrix read)
        Bh = ttnn.repeat_interleave(self._to_heads(Bf, B, 1, G, N), H // G, dim=1)  # (B, H, 1, N)
        Ch = ttnn.repeat_interleave(self._to_heads(Cf, B, 1, G, N), H // G, dim=1)
        dt_h = self._to_heads(dt, B, 1, H, 1)
        return _ssm_cache.mamba_ssm_step(self._state, X, Bh, Ch, dt_h, self._A, self._D, self.ckc)

    # ----------------------------- forward ---------------------------- #
    def __call__(self, hidden_states, **kwargs):
        hs = self._fp32(hidden_states)
        if hs.layout != ttnn.TILE_LAYOUT:
            hs = ttnn.to_layout(hs, ttnn.TILE_LAYOUT)
        shape = list(hs.shape)
        B, T = shape[0], shape[1]
        H, HD, N = self.num_heads, self.head_dim, self.ssm_state_size
        I = self.intermediate_size
        G = self.n_groups
        consts = None if getattr(self, "_cache_mode", None) == "decode" else self._get_consts(B, T)

        # 1. in_proj  -> (B, T, 10304)
        cg = self.device.compute_with_storage_grid_size()
        if B * T <= _dram_mm.TILE:  # decode: one tile row, spread N over the full grid
            pc = _dram_mm.mcast1d_config(self.device, int(hs.shape[-1]), int(self._w_in.shape[-1]))
            proj = ttnn.matmul(hs, self._w_in, compute_kernel_config=self.ckc, program_config=pc)
        else:
            proj = _dram_mm.from_rows(
                ttnn.matmul(
                    _dram_mm.as_rows(hs),
                    self._w_in,
                    compute_kernel_config=self.ckc,
                    core_grid=ttnn.CoreGrid(y=cg.y, x=cg.x),
                ),
                B,
                T,
            )

        # 2. split: gate(I) | hbc(conv_dim) | dt(H)
        gate = ttnn.slice(proj, [0, 0, 0], [B, T, I])
        hbc = ttnn.slice(proj, [0, 0, I], [B, T, I + self.conv_dim])
        dt = ttnn.slice(proj, [0, 0, I + self.conv_dim], [B, T, I + self.conv_dim + H])
        ttnn.deallocate(proj)

        mode = getattr(self, "_cache_mode", None)
        if mode == "decode":
            Y = self._decode_core(hbc, dt, B * T)
        else:
            Y = self._prefill_core(hbc, dt, B, T, consts, fill=(mode == "fill"))

        # 11. back to (B, T, I)
        y = _ssm_cache.from_heads(Y, B, T, self.num_heads, self.head_dim)
        ttnn.deallocate(Y)

        # 12. gated grouped RMSNorm (norm_before_gate=False).
        # `self.gated_norm`, when set by the composing pipeline, supplies this
        # step from the graduated `zamba2_r_m_s_norm_gated` stub instead of the
        # inline copy below. Same math, same (y, gate) contract; its output
        # feeds out_proj exactly as the inline path's does.
        if getattr(self, "gated_norm", None) is not None:
            y = self.gated_norm(y, gate)
            out = self._out_proj(y, B, T)
            ttnn.deallocate(y)
            if self._shard:
                out = ttnn.all_reduce(out, cluster_axis=self._tp_axis, topology=ttnn.Topology.Linear)
            return ttnn.typecast(out, ttnn.bfloat16)

        g_silu = ttnn.silu(gate)
        ttnn.deallocate(gate)
        y = ttnn.multiply(y, g_silu)
        ttnn.deallocate(g_silu)

        gs = self.norm_group_size
        if B * T <= _dram_mm.TILE:  # decode: one tile row, no ROW_MAJOR round trip
            y = _ssm_cache.group_rms(self.device, y, self._norm_w_full, gs, self.norm_eps, self._consts, self.ckc)
            return self._finish(y, B, T)
        ng = I // gs
        y_rm = ttnn.to_layout(y, ttnn.ROW_MAJOR_LAYOUT)
        y_g = ttnn.reshape(y_rm, [B, T * ng, gs])
        y_g = ttnn.to_layout(y_g, ttnn.TILE_LAYOUT)
        y_n = ttnn.rms_norm(y_g, weight=self._norm_ones, epsilon=self.norm_eps, compute_kernel_config=self.ckc)
        ttnn.deallocate(y_g)
        y_n_rm = ttnn.to_layout(y_n, ttnn.ROW_MAJOR_LAYOUT)
        y_n_rm = ttnn.reshape(y_n_rm, [B, T, I])
        y = ttnn.to_layout(y_n_rm, ttnn.TILE_LAYOUT)
        y = ttnn.multiply(y, self._norm_w_full)

        # 13. out_proj (row-parallel under TP): sum the per-chip partial sums so
        #     every TP chip holds the full mixer output (readback keeps chip 0).
        return self._finish(y, B, T)

    def _finish(self, y, B, T):
        """out_proj (row-parallel under TP: all_reduce the per-chip partials)."""
        out = self._out_proj(y, B, T)  # (B, T, hidden_size)
        ttnn.deallocate(y)
        if self._shard:
            out = ttnn.all_reduce(out, cluster_axis=self._tp_axis, topology=ttnn.Topology.Linear)
        return ttnn.typecast(out, ttnn.bfloat16)


# Module-level `build` — primary test entry point.
def build(device, torch_module=None):
    return TtNemotronHMamba2Mixer.build(device, torch_module)


# Backward-compatible slug shim.
def nemotron_h_mamba2_mixer(device, torch_module=None):
    return TtNemotronHMamba2Mixer.build(device, torch_module)
