# >>> MACHINE-GENERATED by `tt_hw_planner bringup --synthesize` <<<
# Review required before trusting on hardware. This body was produced
# by an LLM from the HF reference source and may contain subtle bugs.
# Backup of the previous stub is at <stub>.before_synth.py.bak.
# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
# SPDX-License-Identifier: Apache-2.0
# >>> MACHINE-GENERATED stub (ADAPT — canonical-wrapper path) <<<
"""Pure-TTNN NemotronH MoE mixer for `nemotron_h_m_o_e`.

The canonical `TtMoeLayer` (models/tt_transformers/tt/mixtral_moe.py) is
structurally inapplicable to this component:

  * It hard-asserts ``num_devices == 8`` — this is a QB2 2x2 = **4-device**
    mesh.
  * It is a top-2-of-8-expert, Meta-naming (``block_sparse_moe.gate``),
    softmax-gated Mixtral router.  NemotronH MoE is top-**6**-of-**128**,
    HF-naming (``gate.weight`` / ``experts.N.{up,down}_proj``),
    **sigmoid**-gated with an additive ``e_score_correction_bias`` and
    ``relu2`` (relu(x)**2) expert MLPs + a shared expert.
  * Its construction path goes through ``ModelArgs(mesh_device=...)`` which
    cannot load this repo's custom HF code (ValueError: custom code).

So this stub computes the forward with native ``ttnn.*`` ops, mirroring the
graduated `nemotron_h_mamba2_mixer` sibling.  The canonical import is retained
per the ADAPT requirement.

HF reference (modeling_nemotron_h.py NemotronHMOE.forward):

    topk_indices, topk_weights = gate(hidden)          # sigmoid+bias, top-6
    out = moe(hidden, topk_indices, topk_weights)      # sum selected experts
    out = out + shared_experts(hidden)

Router (n_group=1, topk_group=1 → group machinery is a no-op):
    logits = hidden @ gate.weight.T            (fp32)
    scores = sigmoid(logits)
    scores_b = scores + e_score_correction_bias
    select top-6 of scores_b ; weights = scores.gather(top6)
    weights = weights / (sum(weights)+1e-20) * routed_scaling_factor

Implemented densely: every expert is evaluated for all tokens, then weighted
by a (tokens, n_experts) routing matrix that is zero for unselected experts
(mathematically identical to the sparse HF loop).
"""
from __future__ import annotations

import torch

import ttnn
from models.demos.nvidia_nemotron_3_5_lightning_30b_a3b_bf16._stubs import _dram_mm
from models.tt_transformers.tt.mixtral_moe import TtMoeLayer  # kept per ADAPT requirement


class TtNemotronHMOE:
    def __init__(self, device, torch_module) -> None:
        self.device = device

        gate = torch_module.gate
        self.top_k = int(torch_module.top_k)
        self.n_routed_experts = int(gate.n_routed_experts)
        self.routed_scaling_factor = float(torch_module.routed_scaling_factor)
        self.norm_topk_prob = bool(torch_module.norm_topk_prob)

        sd = torch_module.state_dict()
        self.hidden_size = sd["gate.weight"].shape[1]

        # ---- router ----
        # gate.weight: (n_experts, hidden) -> store transposed (hidden, n_experts)
        self._gate_w = self._dev(sd["gate.weight"].t().contiguous().float())
        bias = sd.get("gate.e_score_correction_bias", None)
        if bias is None:
            bias = torch.zeros(self.n_routed_experts)
        self._bias = self._dev(bias.float().reshape(1, 1, self.n_routed_experts))

        # ---- tensor-parallel (expert-parallel) config --------------------
        # ONLY shard under the shard runner; the single-device .last_good_native
        # path stays byte-identical (TP=1 => replicated, exactly as before).
        # MoE TP = EXPERT-parallel: a disjoint subset of the 128 routed experts
        # lives on each chip (weights split, not a single expert row/col-split).
        # The router is replicated (full W on every chip), a per-chip sharded
        # selector picks that chip's routing-weight columns, and the per-chip
        # partial mixture is all_reduced over the TP axis to recover the full
        # 128-expert sum. The shared expert (replicated) is added once AFTER the
        # reduce. The math is identical to the dense single-device golden.
        import os as _os

        dev = self.device
        try:
            _is_mesh = isinstance(dev, ttnn.MeshDevice)
        except AttributeError:
            _is_mesh = False
        _mesh_shape = list(dev.shape) if _is_mesh else [1, 1]
        _shard = bool(_os.environ.get("TT_HW_PLANNER_SHARD_RUN")) and _is_mesh
        TP = _mesh_shape[-1] if _shard else 1
        _shard = _shard and TP > 1 and (self.n_routed_experts % TP == 0)
        self._shard = _shard
        self._TP = TP
        self._tp_axis = len(_mesh_shape) - 1
        self._mesh_shape = _mesh_shape

        # ---- routed experts (relu2 MLP, no bias) ----
        E = self.n_routed_experts
        # experts.{up,down}_proj are single 3D Parameters (E, out, in) -- NOT
        # per-expert nn.Linear submodules (see NemotronHExperts.__init__) --
        # so each expert's matrix is a transpose() of a slice, not a keyed
        # `experts.{e}.up_proj.weight` lookup.
        if _shard:
            Eloc = E // TP
            up_stack = sd["experts.up_proj"].transpose(-1, -2).contiguous().to(torch.bfloat16)  # (E, in, inter)
            dn_stack = sd["experts.down_proj"].transpose(-1, -2).contiguous().to(torch.bfloat16)  # (E, inter, in)

            # FOLDED expert bank: chip d's local experts concatenated along the
            # expert-output axis so the whole bank is ONE up and ONE down matmul
            # (was one matmul pair per expert). Built on host and sharded on dim 0
            # so chip d gets experts [d*Eloc, (d+1)*Eloc).
            def _folded(stack, cat_dim):
                chunk = torch.stack(
                    [torch.cat([stack[d * Eloc + j] for j in range(Eloc)], dim=cat_dim) for d in range(TP)], dim=0
                )
                t = ttnn.from_torch(
                    chunk,
                    dtype=ttnn.bfloat4_b,
                    layout=ttnn.TILE_LAYOUT,
                    device=dev,
                    mesh_mapper=ttnn.ShardTensor2dMesh(dev, mesh_shape=_mesh_shape, dims=(None, 0)),
                )
                return ttnn.reshape(t, list(chunk.shape[1:]))

            self._up_cat = _folded(up_stack, 1)  # (hidden, Eloc*inter)
            self._down_cat = _folded(dn_stack, 0)  # (Eloc*inter, hidden)
            # decode copy of the down bank, DRAM-sharded (see _dram_mm)
            self._down_dram = _dram_mm.upload_weight(
                dev,
                torch.stack([torch.cat([dn_stack[d * Eloc + j] for j in range(Eloc)], dim=0) for d in range(TP)]),
                _mesh_shape,
            )
            # per-chip expert selector: sel[d] is a one-hot [E, Eloc] that maps the
            # replicated full router weights W (.,.,E) to this chip's Eloc columns
            # via a matmul; sharded on dim0 so chip d gets sel[d].
            sel = torch.zeros(TP, E, Eloc)
            for d in range(TP):
                for j in range(Eloc):
                    sel[d, d * Eloc + j, j] = 1.0
            _sel_sh = ttnn.from_torch(
                sel,
                dtype=ttnn.float32,
                layout=ttnn.TILE_LAYOUT,
                device=dev,
                mesh_mapper=ttnn.ShardTensor2dMesh(dev, mesh_shape=_mesh_shape, dims=(None, 0)),
            )
            # squeeze to 2-D: a rank-3 rhs with batch 1 against a batch-B lhs is
            # a PARTIAL batch broadcast, which hangs ttnn.matmul (measured
            # 2026-09-06). A 2-D rhs broadcasts safely over any batch.
            self._sel = ttnn.reshape(_sel_sh, [E, Eloc])
            self._Eloc = Eloc
        else:
            up_full = sd["experts.up_proj"].transpose(-1, -2).contiguous()  # (E, in, inter)
            dn_full = sd["experts.down_proj"].transpose(-1, -2).contiguous()  # (E, inter, in)
            self._up_cat = self._devw(torch.cat(list(up_full), dim=1))
            self._down_cat = self._devw4(torch.cat(list(dn_full), dim=0))
            self._down_dram = _dram_mm.upload_weight(dev, torch.cat(list(dn_full), dim=0))
            self._sel = None
            self._Eloc = E

        # One-hot (Eloc, Eloc*inter) expander: row j is 1 over expert j's slice
        # of the folded activation (same on every chip -> replicated).
        self._inter = int(sd["experts.up_proj"].shape[1])
        self._expand = self._upload(
            torch.repeat_interleave(torch.eye(self._Eloc), self._inter, dim=1).to(torch.bfloat16), ttnn.bfloat16
        )

        # ---- shared expert ----
        self._sh_up = self._devw(sd["shared_experts.up_proj.weight"].t().contiguous())
        self._sh_down = self._devw(sd["shared_experts.down_proj.weight"].t().contiguous())

        self.ckc = ttnn.WormholeComputeKernelConfig(
            math_fidelity=ttnn.MathFidelity.HiFi4,
            math_approx_mode=False,
            fp32_dest_acc_en=True,
            packer_l1_acc=True,
        )
        # LoFi is safe for the bf8_b expert MLP matmuls (weights already
        # lossy); the router/topk-selector matmuls above keep self.ckc (HiFi4)
        # for topk precision, matching the sibling nemotron_h_experts.py.
        self._expert_ckc = ttnn.WormholeComputeKernelConfig(
            math_fidelity=ttnn.MathFidelity.LoFi,
            math_approx_mode=False,
            fp32_dest_acc_en=True,
            packer_l1_acc=True,
        )

    # ------------------------------------------------------------------ #
    @classmethod
    def build(cls, device, torch_module):
        return cls(device, torch_module)

    # ----------------------------- helpers ---------------------------- #
    def _is_mesh(self):
        try:
            if isinstance(self.device, ttnn.MeshDevice):
                return True
        except AttributeError:
            pass
        return hasattr(self.device, "get_device_ids") or hasattr(self.device, "get_devices")

    def _upload(self, torch_tensor, dtype, layout=ttnn.TILE_LAYOUT):
        if self._is_mesh():
            try:
                return ttnn.from_torch(
                    torch_tensor,
                    dtype=dtype,
                    layout=layout,
                    device=self.device,
                    mesh_mapper=ttnn.ReplicateTensorToMesh(self.device),
                )
            except Exception:
                pass
        return ttnn.from_torch(torch_tensor, dtype=dtype, layout=layout, device=self.device)

    def _dev(self, torch_tensor, layout=ttnn.TILE_LAYOUT):
        """fp32 constant, mesh-replicated."""
        return self._upload(torch_tensor.float(), ttnn.float32, layout)

    def _devw(self, torch_tensor, layout=ttnn.TILE_LAYOUT):
        """bf8_b weight, mesh-replicated (quarters DRAM vs fp32 for the 128 experts)."""
        return self._upload(torch_tensor.to(torch.bfloat16), ttnn.bfloat8_b, layout)

    def _devw4(self, torch_tensor, layout=ttnn.TILE_LAYOUT):
        """bf4_b weight -- one rung lower than _devw, for the down-proj dtype knob."""
        return self._upload(torch_tensor.to(torch.bfloat16), ttnn.bfloat4_b, layout)

    def _fp32(self, t):
        if isinstance(t, ttnn.Tensor):
            if t.dtype != ttnn.float32:
                return ttnn.typecast(t, ttnn.float32)
            return t
        return self._dev(t)

    # ------------------------------ forward --------------------------- #
    def __call__(self, hidden_states, **kwargs):
        hs = self._fp32(hidden_states)
        if hs.layout != ttnn.TILE_LAYOUT:
            hs = ttnn.to_layout(hs, ttnn.TILE_LAYOUT)
        shape = list(hs.shape)
        B, T = shape[0], shape[1]
        E = self.n_routed_experts

        # ---------------- router (fp32) ----------------
        logits = ttnn.matmul(hs, self._gate_w, compute_kernel_config=self.ckc)  # (B,T,E)
        scores = ttnn.sigmoid(logits)  # (B,T,E) fp32
        ttnn.deallocate(logits)
        choice = ttnn.add(scores, self._bias)  # selection scores (B,T,E)

        # Top-k selection via a FULLY-FP32 ALL-PAIRS RANK (NOT bf16 ttnn.topk).
        # Measured: bf16 topk's threshold rounds the 6th/7th-of-128 boundary
        # scores equal -> over/under-selects -> PCC caps ~0.979. The rank
        # count is exact in fp32. rank_i = #{j : choice_j > choice_i}; the
        # top_k experts are those with rank < top_k.
        bb = ttnn.reshape(choice, [B, T, 1, E])  # (B,T,1,E): [.,.,0,j]=choice_j
        a_col = ttnn.transpose(bb, 2, 3)  # (B,T,E,1): [.,.,i,0]=choice_i
        gt = ttnn.gt(bb, a_col)  # broadcast to (B,T,E,E): [.,.,i,j] = choice_j > choice_i, no E x E repeat
        ttnn.deallocate(bb)
        ttnn.deallocate(a_col)
        gt_f = ttnn.typecast(gt, ttnn.float32)
        ttnn.deallocate(gt)
        rank = ttnn.sum(gt_f, dim=3)  # (B,T,E): rank_i = #{j: choice_j>choice_i}
        ttnn.deallocate(gt_f)
        if list(rank.shape)[-1] != E:
            rank = ttnn.reshape(rank, [B, T, E])
        mask = ttnn.lt(rank, float(self.top_k))  # (B,T,E) 1.0/0.0
        ttnn.deallocate(rank)
        ttnn.deallocate(choice)
        if mask.dtype != ttnn.float32:
            mask = ttnn.typecast(mask, ttnn.float32)

        # gather weights from `scores` (NOT choice), normalize over the top-k, scale
        selected = ttnn.multiply(scores, mask)  # (B,T,E)
        ttnn.deallocate(scores)
        ttnn.deallocate(mask)
        if self.norm_topk_prob:
            denom = ttnn.sum(selected, dim=-1, keepdim=True)  # (B,T,1)
            denom = ttnn.add(denom, 1e-20)
            W = ttnn.multiply(selected, ttnn.reciprocal(denom))
            ttnn.deallocate(selected)
            ttnn.deallocate(denom)
        else:
            W = selected
        W = ttnn.multiply(W, self.routed_scaling_factor)  # (B,T,E) fp32

        # Under expert-parallel, project the replicated full W (.,.,E) down to
        # THIS chip's Eloc routing columns (sel[d] one-hot) so they
        # lines up with the folded bank's local expert slices.
        if self._shard:
            W_use = ttnn.matmul(W, self._sel, compute_kernel_config=self.ckc)  # (B,T,Eloc)
            ttnn.deallocate(W)
        else:
            W_use = W

        # ---------------- experts (dense, fp32-accumulated mixture) ----------------
        # HF sums the top-k weighted expert outputs in fp32 (topk_weights.dtype),
        # so accumulate in fp32; bf16 expert weights/matmuls with HiFi4 fp32 acc.
        hs_bf = ttnn.typecast(hs, ttnn.bfloat16)
        # Folded bank: one up matmul over all local experts, relu2, scale each
        # expert's slice by its routing weight (expanded to the folded width),
        # then one down matmul whose K reduction is the weighted expert sum.
        act = ttnn.linear(
            hs_bf, self._up_cat, compute_kernel_config=self._expert_ckc, activation="relu", dtype=ttnn.bfloat8_b
        )
        w_wide = ttnn.matmul(W_use, self._expand, compute_kernel_config=self.ckc, dtype=ttnn.bfloat8_b)
        # relu2 = square fused into the routing-weight multiply (one pass over act)
        act = ttnn.multiply(
            act, w_wide, dtype=ttnn.bfloat8_b, input_tensor_a_activations=[ttnn.UnaryOpType.SQUARE]
        )  # bf8_b halves the down matmul's activation read
        ttnn.deallocate(w_wide)
        if B * T <= _dram_mm.TILE:  # decode: stream the DRAM-sharded bank
            hid = int(hs_bf.shape[-1])
            out = _dram_mm.matmul(
                self.device, ttnn.reshape(act, [1, B * T, int(act.shape[-1])]), self._down_dram, hid, self._expert_ckc
            )
            out = ttnn.reshape(out, [B, T, hid])
        else:
            out = ttnn.matmul(
                act, self._down_cat, compute_kernel_config=self._expert_ckc, dtype=ttnn.float32
            )  # (B,T,hidden) fp32
        ttnn.deallocate(act)
        ttnn.deallocate(W_use)

        # Sum each chip's partial expert mixture into the full 128-expert result
        # (every chip on the TP axis then holds the complete routed sum).
        if self._shard:
            out = ttnn.all_reduce(out, cluster_axis=self._tp_axis, topology=ttnn.Topology.Linear)

        # ---------------- shared expert (fp32) ----------------
        s_act = ttnn.linear(hs_bf, self._sh_up, compute_kernel_config=self._expert_ckc, activation="relu")
        s_act = ttnn.square(s_act)
        s_down = ttnn.matmul(s_act, self._sh_down, compute_kernel_config=self._expert_ckc)
        ttnn.deallocate(s_act)
        ttnn.deallocate(hs_bf)
        s_down_f = ttnn.typecast(s_down, ttnn.float32)
        ttnn.deallocate(s_down)

        out = ttnn.add(out, s_down_f)  # (B,T,hidden) fp32
        ttnn.deallocate(s_down_f)
        return out


# Module-level `build` — primary test entry point.
def build(device, torch_module=None):
    return TtNemotronHMOE.build(device, torch_module)


# Backward-compat module-level shim with the component's lowercase slug name.
def nemotron_h_m_o_e(device, torch_module=None):
    return TtNemotronHMOE.build(device, torch_module)
