"""Learned capture driver for AutoencoderKLQwenImage.

Auto-generated by auto_capture_driver_onboard. Do not edit by hand --
re-run the auto-onboard flow if the driver becomes stale.
"""
from scripts.tt_hw_planner.capture_drivers import register_capture_driver


def driver(model, sample_input=None):
    try:
        import torch

        try:
            model.eval()
        except Exception:
            pass

        try:
            p = next(model.parameters())
            device = p.device
            dtype = p.dtype
        except Exception:
            device = torch.device("cpu")
            dtype = torch.float32

        in_channels = 3
        z_dim = 16
        try:
            cfg = getattr(model, "config", None)
            if cfg is not None:
                z_dim = int(getattr(cfg, "z_dim", z_dim))
                in_channels = int(getattr(cfg, "in_channels", in_channels))
        except Exception:
            pass

        def make_sample(t, hw):
            return torch.randn(1, in_channels, t, hw, hw, device=device, dtype=dtype)

        candidates = []
        if sample_input is not None:
            try:
                if torch.is_tensor(sample_input):
                    candidates.append(sample_input.to(device=device, dtype=dtype))
            except Exception:
                pass
        for hw in (64, 32, 96, 128):
            for t in (1, 5, 9):
                candidates.append(None)  # placeholder, built lazily below

        succeeded = False
        with torch.no_grad():
            idx = 0
            for hw in (64, 32, 96, 128):
                if succeeded:
                    break
                for t in (1, 5, 9):
                    if succeeded:
                        break
                    trial_tensors = []
                    if idx == 0 and sample_input is not None:
                        try:
                            if torch.is_tensor(sample_input):
                                trial_tensors.append(sample_input.to(device=device, dtype=dtype))
                        except Exception:
                            pass
                    idx += 1
                    try:
                        trial_tensors.append(make_sample(t, hw))
                    except Exception:
                        pass
                    for sample in trial_tensors:
                        try:
                            model(sample, sample_posterior=True, return_dict=True)
                            succeeded = True
                            break
                        except Exception:
                            continue

        try:
            with torch.no_grad():
                sample = make_sample(1, 64)
                latent = None
                if hasattr(model, "encode"):
                    try:
                        enc_out = model.encode(sample)
                    except Exception:
                        enc_out = None
                    if enc_out is not None:
                        try:
                            if hasattr(enc_out, "latent_dist"):
                                try:
                                    latent = enc_out.latent_dist.mode()
                                except Exception:
                                    latent = enc_out.latent_dist.sample()
                            elif torch.is_tensor(enc_out):
                                latent = enc_out
                        except Exception:
                            latent = None
                if latent is None:
                    try:
                        latent = torch.randn(1, z_dim, 1, 8, 8, device=device, dtype=dtype)
                    except Exception:
                        latent = None
                if latent is not None and hasattr(model, "decode"):
                    try:
                        model.decode(latent)
                    except Exception:
                        pass
        except Exception:
            pass

        try:
            with torch.no_grad():
                for hw in (32, 64):
                    try:
                        latent2 = torch.randn(1, z_dim, 1, hw // 8, hw // 8, device=device, dtype=dtype)
                        if hasattr(model, "decode"):
                            model.decode(latent2)
                    except Exception:
                        continue
        except Exception:
            pass
    except Exception:
        pass
    return None


@register_capture_driver(matcher=lambda m: type(m).__name__ == "AutoencoderKLQwenImage")
def _registered_driver(model, sample_input=None):
    import inspect as _insp

    try:
        _p = [
            q
            for q in _insp.signature(driver).parameters.values()
            if q.kind in (q.POSITIONAL_ONLY, q.POSITIONAL_OR_KEYWORD)
        ]
        driver(model) if len(_p) <= 1 else driver(model, sample_input)
    except Exception:
        pass
