"""Learned capture driver for QwenImageTransformer2DModel.

Auto-generated by auto_capture_driver_onboard. Do not edit by hand --
re-run the auto-onboard flow if the driver becomes stale.
"""
from scripts.tt_hw_planner.capture_drivers import register_capture_driver


def driver(model, sample_input=None):
    try:
        import torch

        was_training = model.training
        model.eval()

        params = list(model.parameters())
        device = params[0].device if params else torch.device("cpu")
        dtype = params[0].dtype if params else torch.float32

        config = getattr(model, "config", None)

        def cfg(name, default):
            if config is None:
                return default
            try:
                if isinstance(config, dict):
                    return config.get(name, default)
                return getattr(config, name, default)
            except Exception:
                return default

        in_channels = cfg("in_channels", 64)
        joint_attention_dim = cfg("joint_attention_dim", 3584)
        guidance_embeds = bool(cfg("guidance_embeds", False))

        batch_size = 1
        frames = 1
        h_patches = 4
        w_patches = 4
        img_seq_len = frames * h_patches * w_patches
        txt_len = 8

        def build_inputs(hs_dtype, ts_kind):
            hidden_states = torch.randn(batch_size, img_seq_len, in_channels, device=device, dtype=hs_dtype)
            encoder_hidden_states = torch.randn(batch_size, txt_len, joint_attention_dim, device=device, dtype=hs_dtype)
            encoder_hidden_states_mask = torch.ones(batch_size, txt_len, device=device, dtype=torch.long)
            if ts_kind == "long":
                timestep = torch.full((batch_size,), 500, device=device, dtype=torch.long)
            else:
                timestep = torch.full((batch_size,), 500.0, device=device, dtype=torch.float32)

            img_shapes = [(frames, h_patches, w_patches)] * batch_size
            txt_seq_lens = [txt_len] * batch_size

            guidance = None
            if guidance_embeds:
                guidance = torch.full((batch_size,), 3.5, device=device, dtype=torch.float32)

            return (
                hidden_states,
                encoder_hidden_states,
                encoder_hidden_states_mask,
                timestep,
                img_shapes,
                txt_seq_lens,
                guidance,
            )

        attempts = []
        for hs_dtype in (dtype, torch.float32):
            for ts_kind in ("float", "long"):
                attempts.append((hs_dtype, ts_kind))

        succeeded = False
        with torch.no_grad():
            for hs_dtype, ts_kind in attempts:
                try:
                    (
                        hidden_states,
                        encoder_hidden_states,
                        encoder_hidden_states_mask,
                        timestep,
                        img_shapes,
                        txt_seq_lens,
                        guidance,
                    ) = build_inputs(hs_dtype, ts_kind)

                    kwargs = dict(
                        hidden_states=hidden_states,
                        encoder_hidden_states=encoder_hidden_states,
                        encoder_hidden_states_mask=encoder_hidden_states_mask,
                        timestep=timestep,
                        img_shapes=img_shapes,
                        txt_seq_lens=txt_seq_lens,
                        return_dict=False,
                    )
                    if guidance is not None:
                        kwargs["guidance"] = guidance

                    model(**kwargs)
                    succeeded = True
                    break
                except Exception:
                    continue

        if not succeeded:
            try:
                pos_embed = getattr(model, "pos_embed", None)
                if pos_embed is not None:
                    try:
                        pos_embed(
                            [(frames, h_patches, w_patches)] * batch_size,
                            [txt_len] * batch_size,
                            device,
                        )
                    except Exception:
                        pass

                img_in = getattr(model, "img_in", None)
                if img_in is not None:
                    try:
                        img_in(torch.randn(batch_size, img_seq_len, in_channels, device=device, dtype=dtype))
                    except Exception:
                        pass

                txt_in = getattr(model, "txt_in", None)
                txt_norm = getattr(model, "txt_norm", None)
                if txt_norm is not None and txt_in is not None:
                    try:
                        t = torch.randn(batch_size, txt_len, joint_attention_dim, device=device, dtype=dtype)
                        txt_in(txt_norm(t))
                    except Exception:
                        pass

                time_text_embed = getattr(model, "time_text_embed", None)
                if time_text_embed is not None:
                    try:
                        hs = torch.randn(batch_size, img_seq_len, in_channels, device=device, dtype=dtype)
                        ts = torch.full((batch_size,), 500.0, device=device, dtype=torch.float32)
                        if guidance_embeds:
                            time_text_embed(
                                ts,
                                torch.full((batch_size,), 3.5, device=device, dtype=torch.float32),
                                hs,
                            )
                        else:
                            time_text_embed(ts, hs)
                    except Exception:
                        pass
            except Exception:
                pass

        if was_training:
            try:
                model.train()
            except Exception:
                pass
    except Exception:
        pass
    return None


@register_capture_driver(matcher=lambda m: type(m).__name__ == "QwenImageTransformer2DModel")
def _registered_driver(model, sample_input=None):
    import inspect as _insp

    try:
        _p = [
            q
            for q in _insp.signature(driver).parameters.values()
            if q.kind in (q.POSITIONAL_ONLY, q.POSITIONAL_OR_KEYWORD)
        ]
        driver(model) if len(_p) <= 1 else driver(model, sample_input)
    except Exception:
        pass
